import type { Property, Testimonial } from './types';

export const COMPANY_INFO = {
  name: 'Osorio & León Group S.A.S',
  sloganKey: 'company.slogan',
  logoUrl: 'https://lh3.googleusercontent.com/pw/AP1GczPVONrjfngMlSIYlLwGZZDIvf4Pg4B2bslt8wiiKOb2zg2Eay0bE93XxfLPlc0TShZzDAKzJ1fe9lIBIODXFeYNUtrn3oBds3GkFZHU1KUWo6xHp9yR_3VuU4zXWRebD4A1NFS7YumdjiBdVuUyKG8=w500-h500-s-no-gm',
  address: 'Manizales, Caldas, Colombia',
  registrationNumber: 'Matricula Arrendador S-MAT-SINT-USC 2025-7',
  phones: ['+57 311 567 3740', '+57 321 278 0607'],
  email: 'osorioyleongroupdigital@gmail.com',
  hoursKey: 'company.hours',
  missionKey: 'company.mission',
  visionKey: 'company.vision',
  values: [
    { nameKey: 'values.commitment.name', descriptionKey: 'values.commitment.description' },
    { nameKey: 'values.transparency.name', descriptionKey: 'values.transparency.description' },
    { nameKey: 'values.professionalism.name', descriptionKey: 'values.professionalism.description' },
    { nameKey: 'values.collaboration.name', descriptionKey: 'values.collaboration.description' },
    { nameKey: 'values.innovation.name', descriptionKey: 'values.innovation.description' },
  ],
};

export const SOCIAL_LINKS: { [key: string]: string } = {
  whatsapp1: 'https://wa.me/573115673740',
  whatsapp2: 'https://wa.me/573212780607',
  facebook: 'https://www.facebook.com/inmobiliariaenmanizales',
  instagram: 'https://www.instagram.com/osorioyleongroup',
  youtube: 'https://www.youtube.com/@OSORIOYLEONGROUP',
  tiktok: 'https://www.tiktok.com/@osorioyleongroup',
  reviews: 'https://g.page/r/CXOeo9LDDy8BEBM/review',
  googleMaps: "https://www.google.com/maps/place/5%C2%B003'31.3%22N+75%C2%B°29'15.3%22W/@5.0586957,-75.488227,19z/data=!3m1!4b1!4m4!3m3!8m2!3d5.0586944!4d-75.4875833?entry=ttu&g_ep=EgoyMDI1MDkyOS4wIKXMDSoASAFQAw%3D%3D",
};

export const ADMIN_CREDENTIALS = {
  user: 'osorioyleongroup@gmail.com',
  pass: 'Contraseña123',
};

export const MOCK_PROPERTIES: Property[] = [
    {
    id: 'prop-casa-premium',
    titulo: 'Espectacular Casa de 145 m² con Estudio y Pérgola Privada en Venta - Ubicación Premium',
    descripcion: 'Ponemos a su disposición esta magnífica casa en un exclusivo conjunto residencial, ideal para familias que valoran el espacio, la seguridad y las amenidades de un club.\n\n**Características de la Propiedad:**\n- Área Construida: 145 m² habitables.\n- Espacios Adicionales: Moderna pérgola privada de 18 m², perfecta para chill out o cenas al aire libre.\n- Distribución: 3 Habitaciones luminosas, 3.5 Baños (incluyendo el social), Estudio independiente, ideal para oficina en casa o biblioteca, Cuarto de servicio completo.\n- Parqueaderos: 2 amplios cupos privados.\n\n**Amenidades Exclusivas del Conjunto (Estilo Club House):**\nEl conjunto ofrece un estilo de vida inigualable con zonas comunes diseñadas para el disfrute de toda la familia:\n- Deportes: Cancha de fútbol.\n- Recreación: Kiosko equipado para asados y zona especial para fogatas.\n- Eventos: Amplio Salón Social.\n- Naturaleza y Relax: Extensas zonas verdes, sendero peatonal y juegos infantiles.',
    departamento: 'Caldas',
    ciudad: 'Manizales',
    barrio_sector: 'Conjunto Residencial Exclusivo',
    estrato: 6,
    tipo_operacion: 'venta',
    tipo_propiedad: 'casa',
    precio: 850000000,
    valor_administracion: 504000,
    es_negociable: false,
    area_construida: 145,
    habitaciones: 3,
    banos_completos: 3,
    parqueaderos: 2,
    estado_inmueble: 'used',
    estado_amoblado: 'sin_amoblar',
    tiene_balcon: false,
    tiene_gimnasio: false,
    tiene_piscina_comun: false,
    tiene_ascensor: false,
    tiene_porteria_24h: true,
    tiene_zonas_verdes: true,
    tiene_cancha_futbol: true,
    tiene_kiosko_asados: true,
    tiene_salon_social: true,
    tiene_juegos_infantiles: true,
    tiene_sendero_peatonal: true,
    imagenes: [
      { id: 'img-cp1', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczNCRNO2hebFUjHqlXBA36iJbp0NkpOvsuwRPDy2SWHciaBCODVQ0pK4GXFQJg2zU06CKWz5WfuINXcwYJu0r7g2InKz2GR6JbP0zjQ_PYFvDdig5AsBS316MoO8c40GQgtLoD3bIhuEUqvGEioi4Qi1=w709-h945-s-no-gm?authuser=0', es_principal: true },
      { id: 'img-cp2', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczN4tBUhnQviotPivhcnRYKi-CkQb2F83_t9VdGeQMxvNlKUAngjdV9DOeNUFkwjmYrJqVaYophCxMuPFb-cvOni6jhww28Es2WdHf4zESY5CyOm_Qzosa6EQS-Fe5We11QVj2sU_l6czmT7hJGMo0Q-=w1260-h945-s-no-gm?authuser=0', es_principal: false },
      { id: 'img-cp3', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczOgufHA2Vdzu2ET8dzG3FNTDKWYvi1_kpi8SuO2MnwEJusPZHvo5X2YmRfB3xwLYikJgqgeA0a2EzhMmg2t-e4fXWIXKu6N0G1ANT5G51awCmlWt1QBUPE0YlExg7rQlg7r7uY3c2ROfv2XgANuozbe=w1260-h945-s-no-gm?authuser=0', es_principal: false },
      { id: 'img-cp4', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczMuw_XrjRJJLZIjVF3PSwvAyM6cXNEj6vHLSXxdyPC0E5hn9u17aj6Qu4KT1w4qX96cMBVJjBqQf-NA0kp21MDRFBnCqOpPwJ0i-6jFWPUVdOQFDLBtqNKRrwfBaLhEDvuiBXzX0J7DdOHP0NPUdfgf=w1260-h945-s-no-gm?authuser=0', es_principal: false },
      { id: 'img-cp5', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczNAyHmYR09GDkdfYc29GnYN_SgdBJTkchzjhouXWpfTW5ZHd3xmlnkUn74rlCQrYtaGJl4Twljp3DHX9N90Upl9RStos2GOig_MOfCdIlQaKN6rPFnfCg-ij5sgIsN8QBAqOUclEkogqQJSGySx7AWP=w1260-h945-s-no-gm?authuser=0', es_principal: false },
      { id: 'img-cp6', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczOgauSjkDzUUyXYPVkDkKtKnFwSQ97TmFnvvbZyZHG80o-sXp42dcWBdTliBZpARDStVxEHp-8KwAjrp1TjiBSUurHzLlgNbehvKVexjZq3bx8eWcURPJtgWEdg9NccuYgRLzaFzbUUXei3VcwczSyR=w1260-h945-s-no-gm?authuser=0', es_principal: false },
      { id: 'img-cp7', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczPH8J6O45MfiadIzKuSWYxoKW8dNCpf92eEXdRerJtOH4rFtS350s3sKtsDAAcJI7T8sduika26v6Sp1wcuZTvT5Ip2uG_l3bt8No-_0KykNMFu7zlpD_ucvgQOqrZeSYYwr20AEYezPAGFN6hHr6HY=w1260-h945-s-no-gm?authuser=0', es_principal: false },
      { id: 'img-cp8', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczNuT9bXCSb_fPNF1jm1bGIs_cCgBgZQIde3X0oi-wXFmpxc4XOjBVTkKa3y4QhYXQXIII7UrN03gYE9jA1R3KpYoqyz-1HxkLJDzJSYIie9MO6f0eLH1x-mxYZxdlZGoUWG__sJdF5AK8C-9pWANm1F=w1260-h945-s-no-gm?authuser=0', es_principal: false },
      { id: 'img-cp9', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczNPTLkyIOrXS-UTg5IFCtce_eqvB0PCHzNeet95mJCaGsFBIV9XA80E0wvNReIbZGXo0y3cB0ltP0q_o8d1Ztg9kvPmVKX0Q5SEWUG2-n_DENUEn3H9uhAkDw4XPe8LFWRQTgMGJ3bN2nJlqufbnitd=w1260-h945-s-no-gm?authuser=0', es_principal: false },
      { id: 'img-cp10', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczNxe1lTrCXELqrz3PIOkPFMHSNVNMFJ5-meh370niGk6cMrES43wrCkWx71zchJjq9rUlDvxHu4JVKrt5rtDwzw9KcvszygSAFtAOe9ppPATwlsU8SQ6Cog4lzlYEBvqrBnZ21c1acMMfZFTYCZS6Fs=w1260-h945-s-no-gm?authuser=0', es_principal: false },
      { id: 'img-cp11', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczPSJOdsuXycvFNi7_TcaEFV7x8KQ9Jm-F5UHUgdxcJhx_WNmR9Q8ssmlSPtR9R9CSNMs38ou__qOtgbFZVi0tdBXOTpSq4lsk92pdDOrVcLVYn3hoTTwS_qHLJ5YTLRGSfHzmY9dP1nKorRSzX8NTN7=w1260-h945-s-no-gm?authuser=0', es_principal: false },
      { id: 'img-cp12', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczOMwSAkWm2g7Cfqt_Irih68owj95ebeCgffHVRvUL_PiI3IBjTrGHJyVYfhxMt6ki0y1ECRD7bSTjcqDort9iLthm0leBDi7Y-Kr6bxnUxbD9ev5XVUH0aM0B0lVSw6qCh78cMTZ-DejinAq-73v2wM=w1260-h945-s-no-gm?authuser=0', es_principal: false },
      { id: 'img-cp13', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczPKZY91_oQNKssnB4ajex1INhUtdnu1AXEhfKFR4_rLFlEajR81F640dR55YsUilBeDn4jS-hADux5HOulMqvErOQxBpn_5YwReLkneu8zFmWdNQdG9seO5OEtu-GcaYk-ghwIBivhpXP76esno8Q-F=w1260-h945-s-no-gm?authuser=0', es_principal: false },
      { id: 'img-cp14', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczNzg62PUxHHccb1tqIS64ETb57qHTUKxk9f3La9SLxSybyVOAXsWu_S9E4fasiy6rtgd9c9_GAXNH9DPy15WHCYg2x-RDC-82-YgkHVeoszpHYkzpLukoYL5XUY3j__BwDCbKNdDnWzi11hiU7j04b3=w1260-h945-s-no-gm?authuser=0', es_principal: false },
      { id: 'img-cp15', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczN_aYdEExxUrJksnflBjPQ3qzU8mMWdJE6VcdzVc9E0vYBrKfXqdV5BXqGUUSCHrrtmpne17xu1dkfzavDKB9w2hIPcTpW_sUY0_Z3zkivujWLyiIaaN-ERmq3fvaZPYZfbjtdHXO2eqSO5OSrAAi-M=w1260-h945-s-no-gm?authuser=0', es_principal: false },
      { id: 'img-cp16', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczM7VgY7MaFnmpPipVY1advv9Ugwdi-0WIpfp7CzvCSjK-2ytQMpHVNC8zgHJ_Qlcd_08S00iXHcyqXSDpM7e3lJ9g_c0XAWZFYI4A96bKq9pBNUt-6i16w4HmbGktpfjilYbEwvcJlCC_dOXin1fluA=w1260-h945-s-no-gm?authuser=0', es_principal: false },
    ],
    es_destacado: false,
    estado_publicacion: 'publicado',
    fecha_publicacion: new Date().toISOString(),
  },
    {
    id: 'prop3',
    titulo: 'Acogedor Apartaestudio en Arriendo en Laureles',
    descripcion: 'Práctico y bien ubicado apartaestudio, cerca a universidades, centros comerciales y rutas de transporte. Totalmente amoblado y listo para habitar. Perfecto para estudiantes o profesionales.',
    departamento: 'Antioquia',
    ciudad: 'Medellín',
    barrio_sector: 'Laureles',
    estrato: 5,
    tipo_operacion: 'arriendo',
    tipo_propiedad: 'apartamento',
    precio: 1800000,
    valor_administracion: 200000,
    es_negociable: false,
    area_construida: 45,
    habitaciones: 1,
    banos_completos: 1,
    parqueaderos: 1,
    estado_inmueble: 'used',
    estado_amoblado: 'amoblado',
    tiene_balcon: true,
    tiene_gimnasio: false,
    tiene_piscina_comun: false,
    tiene_ascensor: true,
    tiene_porteria_24h: true,
    tiene_zonas_verdes: false,
    tiene_cancha_futbol: false,
    tiene_kiosko_asados: false,
    tiene_salon_social: true,
    tiene_juegos_infantiles: false,
    tiene_sendero_peatonal: false,
    imagenes: [
      { id: 'img3a', url_imagen: 'https://images.pexels.com/photos/271624/pexels-photo-271624.jpeg', es_principal: true },
    ],
    es_destacado: false,
    estado_publicacion: 'publicado',
    fecha_publicacion: new Date().toISOString(),
  },
  {
    id: 'prop-altos-cipres',
    titulo: 'Apartamento en Venta en Altos de Ciprés',
    descripcion: 'Apartamento ubicado en Altos de Ciprés, cerca de la Universidad de Manizales. Cuenta con parqueadero para residentes y visitantes.',
    departamento: 'Caldas',
    ciudad: 'Manizales',
    barrio_sector: 'Altos de Ciprés',
    estrato: 5,
    tipo_operacion: 'venta',
    tipo_propiedad: 'apartamento',
    precio: 300000000,
    valor_administracion: 320000,
    es_negociable: false,
    area_construida: 67.54,
    habitaciones: 2,
    banos_completos: 2,
    parqueaderos: 1,
    estado_inmueble: 'used',
    estado_amoblado: 'sin_amoblar',
    tiene_balcon: false,
    tiene_gimnasio: false,
    tiene_piscina_comun: false,
    tiene_ascensor: true,
    tiene_porteria_24h: true,
    tiene_zonas_verdes: true,
    tiene_cancha_futbol: false,
    tiene_kiosko_asados: false,
    tiene_salon_social: true,
    tiene_juegos_infantiles: true,
    tiene_sendero_peatonal: true,
    imagenes: [
      { id: 'img-ac1', url_imagen: 'https://images.pexels.com/photos/1571460/pexels-photo-1571460.jpeg', es_principal: true },
      { id: 'img-ac2', url_imagen: 'https://images.pexels.com/photos/2724749/pexels-photo-2724749.jpeg', es_principal: false },
      { id: 'img-ac3', url_imagen: 'https://images.pexels.com/photos/6585620/pexels-photo-6585620.jpeg', es_principal: false },
    ],
    es_destacado: false,
    estado_publicacion: 'publicado',
    fecha_publicacion: new Date().toISOString(),
  },
  {
    id: 'prop-lusitania',
    titulo: 'Apartamento Esquinero en Venta en Lusitania',
    descripcion: 'Luminoso apartamento esquinero en el barrio Lusitania. Dispone de 3 habitaciones, cocina integral, zona de ropas y parqueadero cubierto. ¡Listo para negociar!',
    departamento: 'Caldas',
    ciudad: 'Manizales',
    barrio_sector: 'Lusitania',
    estrato: 4,
    tipo_operacion: 'venta',
    tipo_propiedad: 'apartamento',
    precio: 220000000,
    valor_administracion: 0,
    es_negociable: true,
    area_construida: 62,
    habitaciones: 3,
    banos_completos: 2,
    parqueaderos: 1,
    estado_inmueble: 'remodeled',
    estado_amoblado: 'sin_amoblar',
    tiene_balcon: false,
    tiene_gimnasio: false,
    tiene_piscina_comun: false,
    tiene_ascensor: false,
    tiene_porteria_24h: false,
    tiene_zonas_verdes: false,
    tiene_cancha_futbol: false,
    tiene_kiosko_asados: false,
    tiene_salon_social: false,
    tiene_juegos_infantiles: false,
    tiene_sendero_peatonal: false,
    imagenes: [
      { id: 'img-lu1', url_imagen: 'https://images.pexels.com/photos/276724/pexels-photo-276724.jpeg', es_principal: true },
      { id: 'img-lu2', url_imagen: 'https://images.pexels.com/photos/439227/pexels-photo-439227.jpeg', es_principal: false },
    ],
    es_destacado: false,
    estado_publicacion: 'publicado',
    fecha_publicacion: new Date().toISOString(),
  },
  {
    id: 'prop-mirador-trebol',
    titulo: 'Lujoso Apartamento en Venta - Mirador del Trébol',
    descripcion: 'Espectacular apartamento en el Edificio Mirador del Trébol. Disfruta de una amplia terraza, 3 cuartos y excelentes zonas comunes como gimnasio, salón social y área de juegos. Incluye 2 parqueaderos.',
    departamento: 'Caldas',
    ciudad: 'Manizales',
    barrio_sector: 'Mirador del Trébol',
    estrato: 6,
    tipo_operacion: 'venta',
    tipo_propiedad: 'apartamento',
    precio: 950000000,
    valor_administracion: 850000,
    es_negociable: false,
    area_construida: 116.91,
    habitaciones: 3,
    banos_completos: 3,
    parqueaderos: 2,
    estado_inmueble: 'used',
    estado_amoblado: 'sin_amoblar',
    tiene_balcon: true,
    tiene_gimnasio: true,
    tiene_piscina_comun: false,
    tiene_ascensor: true,
    tiene_porteria_24h: true,
    tiene_zonas_verdes: true,
    tiene_cancha_futbol: false,
    tiene_kiosko_asados: true,
    tiene_salon_social: true,
    tiene_juegos_infantiles: true,
    tiene_sendero_peatonal: true,
    imagenes: [
      { id: 'img-mt1', url_imagen: 'https://images.pexels.com/photos/1643383/pexels-photo-1643383.jpeg', es_principal: true },
      { id: 'img-mt2', url_imagen: 'https://images.pexels.com/photos/1954524/pexels-photo-1954524.jpeg', es_principal: false },
      { id: 'img-mt3', url_imagen: 'https://images.pexels.com/photos/3935320/pexels-photo-3935320.jpeg', es_principal: false },
    ],
    es_destacado: true,
    estado_publicacion: 'publicado',
    fecha_publicacion: new Date().toISOString(),
  },
  {
    id: 'prop-robles-bellasuiza',
    titulo: 'Apartamento con Vista en Robles de Bella Suiza',
    descripcion: 'Moderno apartamento en un piso 14 en Robles de Bella Suiza, con balcón y una increíble vista a la avenida Kevin Ángel. Incluye parqueadero y depósito. El edificio cuenta con piscina, gimnasio y salón social.',
    departamento: 'Caldas',
    ciudad: 'Manizales',
    barrio_sector: 'Bella Suiza',
    estrato: 6,
    tipo_operacion: 'venta',
    tipo_propiedad: 'apartamento',
    precio: 435000000,
    valor_administracion: 450000,
    es_negociable: false,
    area_construida: 69,
    habitaciones: 3,
    banos_completos: 2,
    parqueaderos: 1,
    estado_inmueble: 'used',
    estado_amoblado: 'sin_amoblar',
    tiene_balcon: true,
    tiene_gimnasio: true,
    tiene_piscina_comun: true,
    tiene_ascensor: true,
    tiene_porteria_24h: true,
    tiene_zonas_verdes: true,
    tiene_cancha_futbol: true,
    tiene_kiosko_asados: false,
    tiene_salon_social: true,
    tiene_juegos_infantiles: true,
    tiene_sendero_peatonal: true,
    imagenes: [
      { id: 'img-rb1', url_imagen: 'https://images.pexels.com/photos/323775/pexels-photo-323775.jpeg', es_principal: true },
      { id: 'img-rb2', url_imagen: 'https://images.pexels.com/photos/221457/pexels-photo-221457.jpeg', es_principal: false },
      { id: 'img-rb3', url_imagen: 'https://images.pexels.com/photos/2102587/pexels-photo-2102587.jpeg', es_principal: false },
    ],
    es_destacado: true,
    estado_publicacion: 'publicado',
    fecha_publicacion: new Date().toISOString(),
  },
  {
    id: 'prop-torres-sanvicente',
    titulo: 'Apartamento en Venta en Torres de San Vicente',
    descripcion: 'Apartamento en Torres de San Vicente con excelentes áreas sociales: piscinas para adultos y niños, cancha múltiple, salón social, terraza y zona BBQ. Incluye una amplia bodega de 8.5 m².',
    departamento: 'Caldas',
    ciudad: 'Manizales',
    barrio_sector: 'San Vicente',
    estrato: 4,
    tipo_operacion: 'venta',
    tipo_propiedad: 'apartamento',
    precio: 330000000,
    valor_administracion: 280000,
    es_negociable: false,
    area_construida: 57,
    habitaciones: 2,
    banos_completos: 2,
    parqueaderos: 1,
    estado_inmueble: 'used',
    estado_amoblado: 'semi_amoblado',
    tiene_balcon: false,
    tiene_gimnasio: false,
    tiene_piscina_comun: true,
    tiene_ascensor: true,
    tiene_porteria_24h: true,
    tiene_zonas_verdes: true,
    tiene_cancha_futbol: true,
    tiene_kiosko_asados: true,
    tiene_salon_social: true,
    tiene_juegos_infantiles: false,
    tiene_sendero_peatonal: false,
    imagenes: [
      { id: 'img-tsv1', url_imagen: 'https://images.pexels.com/photos/1105754/pexels-photo-1105754.jpeg', es_principal: true },
      { id: 'img-tsv2', url_imagen: 'https://images.pexels.com/photos/176390/pexels-photo-176390.jpeg', es_principal: false },
    ],
    es_destacado: false,
    estado_publicacion: 'publicado',
    fecha_publicacion: new Date().toISOString(),
  },
  {
    id: 'prop-apartaestudio-palermo',
    titulo: 'Apartaestudio en Venta en Abudhabi, Palermo',
    descripcion: 'Acogedor apartaestudio de 3 ambientes en el sector de Palermo. Ubicado en un piso 4, cuenta con parqueadero privado, depósito y ascensor. Ideal para inversión o para vivir.',
    departamento: 'Caldas',
    ciudad: 'Manizales',
    barrio_sector: 'Palermo',
    estrato: 6,
    tipo_operacion: 'venta',
    tipo_propiedad: 'apartamento',
    precio: 180000000,
    valor_administracion: 190000,
    es_negociable: false,
    area_construida: 44,
    habitaciones: 1,
    banos_completos: 1,
    parqueaderos: 1,
    estado_inmueble: 'new',
    estado_amoblado: 'sin_amoblar',
    tiene_balcon: false,
    tiene_gimnasio: false,
    tiene_piscina_comun: false,
    tiene_ascensor: true,
    tiene_porteria_24h: true,
    tiene_zonas_verdes: false,
    tiene_cancha_futbol: false,
    tiene_kiosko_asados: false,
    tiene_salon_social: false,
    tiene_juegos_infantiles: false,
    tiene_sendero_peatonal: false,
    imagenes: [
      { id: 'img-ap1', url_imagen: 'https://images.pexels.com/photos/545045/pexels-photo-545045.jpeg', es_principal: true },
      { id: 'img-ap2', url_imagen: 'https://images.pexels.com/photos/209291/pexels-photo-209291.jpeg', es_principal: false },
    ],
    es_destacado: false,
    estado_publicacion: 'publicado',
    fecha_publicacion: new Date().toISOString(),
  }
];

// FIX: Added parentheses around the intersection type to ensure it's an array of the combined type,
// not an intersection of a type and an array type.
export const TESTIMONIALS: (Omit<Testimonial, 'comment'> & { commentKey: string })[] = [
  {
    name: 'Carlos Mendoza',
    rating: 5,
    commentKey: 'testimonials.carlosMendoza',
    avatar: 'https://randomuser.me/api/portraits/men/32.jpg',
  },
  {
    name: 'Ana Sofía Restrepo',
    rating: 5,
    commentKey: 'testimonials.anaSofiaRestrepo',
    avatar: 'https://randomuser.me/api/portraits/women/44.jpg',
  },
  {
    name: 'Javier Correa',
    rating: 4.5,
    commentKey: 'testimonials.javierCorrea',
    avatar: 'https://randomuser.me/api/portraits/men/46.jpg',
  },
  {
    name: 'Lucía Vélez',
    rating: 5,
    commentKey: 'testimonials.luciaVelez',
    avatar: 'https://randomuser.me/api/portraits/women/31.jpg',
  },
  {
    name: 'Ricardo Palacio',
    rating: 4,
    commentKey: 'testimonials.ricardoPalacio',
    avatar: 'https://randomuser.me/api/portraits/men/60.jpg',
  },
  {
    name: 'Isabella Giraldo',
    rating: 5,
    commentKey: 'testimonials.isabellaGiraldo',
    avatar: 'https://randomuser.me/api/portraits/women/68.jpg',
  },
  {
    name: 'Mateo Arango',
    rating: 4.5,
    commentKey: 'testimonials.mateoArango',
    avatar: 'https://randomuser.me/api/portraits/men/78.jpg',
  },
  {
    name: 'Valentina Hoyos',
    rating: 5,
    commentKey: 'testimonials.valentinaHoyos',
    avatar: 'https://randomuser.me/api/portraits/women/8.jpg',
  },
  {
    name: 'Andrés Castaño',
    rating: 4,
    commentKey: 'testimonials.andresCastano',
    avatar: 'https://randomuser.me/api/portraits/men/11.jpg',
  },
  {
    name: 'Daniela Franco',
    rating: 5,
    commentKey: 'testimonials.danielaFranco',
    avatar: 'https://randomuser.me/api/portraits/women/17.jpg',
  }
];