import type { Property } from './types';

export const COMPANY_INFO = {
  name: 'Osorio & León Group S.A.S',
  slogan: '“MÁS QUE PROPIEDADES, CONSTRUIMOS CONFIANZA”',
  logoUrl: 'data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAxMDAgMTAwIj48Y2lyY2xlIGN4PSI1MCIgY3k9IjUwIiByPSI1MCIgZmlsbD0iIzE1M0I2NyIvPjxwYXRoIGQ9Ik01MCAyMCBMMjAgNDUgTDMwIDQ1IEwzMCA4MCBMNzAgODAgTDcwIDQ1IEw4MCA0NSBaIiBmaWxsPSJ3aGl0ZSIvPjwvc3ZnPg==',
  address: 'Manizales, Caldas, Colombia',
  phones: ['+57 311 567 3740', '+57 321 278 0607'],
  email: 'contacto@osorioleongroup.com',
  hours: 'Lunes a Viernes: 9am - 6pm',
  mission: 'Brindar servicios inmobiliarios integrales y personalizados, promoviendo la excelencia en el trato humano y profesional de nuestros agentes, comprometidos a asesorar y acompañar a nuestros clientes en todas las etapas del proceso, ya sea asesoría, compra, venta o alquiler de propiedades, garantizando la transparencia, confiabilidad y satisfacción en cada transacción.',
  vision: 'Ser la inmobiliaria líder en Manizales y Caldas para el año 2.027 y reconocida a nivel nacional e internacional para el año 2030 por nuestra integridad, innovación y compromiso con la excelencia en el servicio al cliente, contribuyendo al desarrollo Urbano y Rural, sostenible con nuestras comunidades.',
  values: [
    { name: 'Compromiso', description: 'nos comprometemos a dar lo mejor de nosotros con nuestros clientes y superar sus expectativas en cada interacción.' },
    { name: 'Transparencia', description: 'actuamos con honestidad y claridad en todas nuestras operaciones y relaciones comerciales.' },
    { name: 'Profesionalismo', description: 'actuamos con integridad y ética en todo momento.' },
    { name: 'Colaboración', description: 'fomentamos un ambiente donde el trabajo en equipo y el apoyo mutuo es fundamental para nuestro éxito.' },
    { name: 'Innovación', description: 'Buscamos constantemente nuevas formas de mejorar y adaptarnos a las demandas del mercado.' },
  ],
};

export const SOCIAL_LINKS: { [key: string]: string } = {
  whatsapp1: 'https://wa.me/573115673740',
  whatsapp2: 'https://wa.me/573212780607',
  facebook: 'https://www.facebook.com/inmobiliariaenmanizales',
  instagram: 'https://www.instagram.com/osorioyleongroup',
  youtube: 'https://www.youtube.com/@OSORIOYLEONGROUP',
  tiktok: 'https://www.tiktok.com/@osorioyleongroup',
  reviews: 'https://g.page/r/CXOeo9LDDy8BEBM/review',
  googleMaps: "https://www.google.com/maps/place/5%C2%B003'31.3%22N+75%C2%B°29'15.3%22W/@5.0586957,-75.488227,19z/data=!3m1!4b1!4m4!3m3!8m2!3d5.0586944!4d-75.4875833?entry=ttu&g_ep=EgoyMDI1MDkyOS4wIKXMDSoASAFQAw%3D%3D",
};

export const ADMIN_CREDENTIALS = {
  user: 'osorioyleongroupdigital@gmail.com',
  pass: 'Admin2024*',
};

export const MOCK_PROPERTIES: Property[] = [
    {
    id: 'prop3',
    titulo: 'Acogedor Apartaestudio en Arriendo en Laureles',
    descripcion: 'Práctico y bien ubicado apartaestudio, cerca a universidades, centros comerciales y rutas de transporte. Totalmente amoblado y listo para habitar. Perfecto para estudiantes o profesionales.',
    ciudad: 'Medellín',
    barrio_sector: 'Laureles',
    tipo_operacion: 'arriendo',
    tipo_propiedad: 'apartamento',
    precio: 1800000,
    es_negociable: false,
    area_construida: 45,
    habitaciones: 1,
    banos_completos: 1,
    parqueaderos: 1,
    tiene_balcon: true,
    tiene_gimnasio: false,
    tiene_piscina_comun: false,
    tiene_ascensor: true,
    tiene_porteria_24h: true,
    imagenes: [
      { id: 'img3a', url_imagen: 'https://images.pexels.com/photos/271624/pexels-photo-271624.jpeg', es_principal: true },
    ],
    es_destacado: false,
    estado_publicacion: 'publicado',
    fecha_publicacion: new Date().toISOString(),
  },
  {
    id: 'prop-altos-cipres',
    titulo: 'Apartamento en Venta en Altos de Ciprés',
    descripcion: 'Apartamento ubicado en Altos de Ciprés, cerca de la Universidad de Manizales. Cuenta con parqueadero para residentes y visitantes.',
    ciudad: 'Manizales',
    barrio_sector: 'Altos de Ciprés',
    tipo_operacion: 'venta',
    tipo_propiedad: 'apartamento',
    precio: 300000000,
    es_negociable: false,
    area_construida: 67.54,
    habitaciones: 2,
    banos_completos: 2,
    parqueaderos: 1,
    tiene_balcon: false,
    tiene_gimnasio: false,
    tiene_piscina_comun: false,
    tiene_ascensor: true,
    tiene_porteria_24h: true,
    imagenes: [
      { id: 'img-ac1', url_imagen: 'https://images.pexels.com/photos/1571460/pexels-photo-1571460.jpeg', es_principal: true },
      { id: 'img-ac2', url_imagen: 'https://images.pexels.com/photos/2724749/pexels-photo-2724749.jpeg', es_principal: false },
      { id: 'img-ac3', url_imagen: 'https://images.pexels.com/photos/6585620/pexels-photo-6585620.jpeg', es_principal: false },
    ],
    es_destacado: false,
    estado_publicacion: 'publicado',
    fecha_publicacion: new Date().toISOString(),
  },
  {
    id: 'prop-lusitania',
    titulo: 'Apartamento Esquinero en Venta en Lusitania',
    descripcion: 'Luminoso apartamento esquinero en el barrio Lusitania. Dispone de 3 habitaciones, cocina integral, zona de ropas y parqueadero cubierto. ¡Listo para negociar!',
    ciudad: 'Manizales',
    barrio_sector: 'Lusitania',
    tipo_operacion: 'venta',
    tipo_propiedad: 'apartamento',
    precio: 220000000,
    es_negociable: true,
    area_construida: 62,
    habitaciones: 3,
    banos_completos: 2,
    parqueaderos: 1,
    tiene_balcon: false,
    tiene_gimnasio: false,
    tiene_piscina_comun: false,
    tiene_ascensor: false,
    tiene_porteria_24h: false,
    imagenes: [
      { id: 'img-lu1', url_imagen: 'https://images.pexels.com/photos/276724/pexels-photo-276724.jpeg', es_principal: true },
      { id: 'img-lu2', url_imagen: 'https://images.pexels.com/photos/439227/pexels-photo-439227.jpeg', es_principal: false },
    ],
    es_destacado: false,
    estado_publicacion: 'publicado',
    fecha_publicacion: new Date().toISOString(),
  },
  {
    id: 'prop-mirador-trebol',
    titulo: 'Lujoso Apartamento en Venta - Mirador del Trébol',
    descripcion: 'Espectacular apartamento en el Edificio Mirador del Trébol. Disfruta de una amplia terraza, 3 cuartos y excelentes zonas comunes como gimnasio, salón social y área de juegos. Incluye 2 parqueaderos.',
    ciudad: 'Manizales',
    barrio_sector: 'Mirador del Trébol',
    tipo_operacion: 'venta',
    tipo_propiedad: 'apartamento',
    precio: 950000000,
    es_negociable: false,
    area_construida: 116.91,
    habitaciones: 3,
    banos_completos: 3,
    parqueaderos: 2,
    tiene_balcon: true,
    tiene_gimnasio: true,
    tiene_piscina_comun: false,
    tiene_ascensor: true,
    tiene_porteria_24h: true,
    imagenes: [
      { id: 'img-mt1', url_imagen: 'https://images.pexels.com/photos/1643383/pexels-photo-1643383.jpeg', es_principal: true },
      { id: 'img-mt2', url_imagen: 'https://images.pexels.com/photos/1954524/pexels-photo-1954524.jpeg', es_principal: false },
      { id: 'img-mt3', url_imagen: 'https://images.pexels.com/photos/3935320/pexels-photo-3935320.jpeg', es_principal: false },
    ],
    es_destacado: true,
    estado_publicacion: 'publicado',
    fecha_publicacion: new Date().toISOString(),
  },
  {
    id: 'prop-robles-bellasuiza',
    titulo: 'Apartamento con Vista en Robles de Bella Suiza',
    descripcion: 'Moderno apartamento en un piso 14 en Robles de Bella Suiza, con balcón y una increíble vista a la avenida Kevin Ángel. Incluye parqueadero y depósito. El edificio cuenta con piscina, gimnasio y salón social.',
    ciudad: 'Manizales',
    barrio_sector: 'Bella Suiza',
    tipo_operacion: 'venta',
    tipo_propiedad: 'apartamento',
    precio: 435000000,
    es_negociable: false,
    area_construida: 69,
    habitaciones: 3,
    banos_completos: 2,
    parqueaderos: 1,
    tiene_balcon: true,
    tiene_gimnasio: true,
    tiene_piscina_comun: true,
    tiene_ascensor: true,
    tiene_porteria_24h: true,
    imagenes: [
      { id: 'img-rb1', url_imagen: 'https://images.pexels.com/photos/323775/pexels-photo-323775.jpeg', es_principal: true },
      { id: 'img-rb2', url_imagen: 'https://images.pexels.com/photos/221457/pexels-photo-221457.jpeg', es_principal: false },
      { id: 'img-rb3', url_imagen: 'https://images.pexels.com/photos/2102587/pexels-photo-2102587.jpeg', es_principal: false },
    ],
    es_destacado: true,
    estado_publicacion: 'publicado',
    fecha_publicacion: new Date().toISOString(),
  },
  {
    id: 'prop-torres-sanvicente',
    titulo: 'Apartamento en Venta en Torres de San Vicente',
    descripcion: 'Apartamento en Torres de San Vicente con excelentes áreas sociales: piscinas para adultos y niños, cancha múltiple, salón social, terraza y zona BBQ. Incluye una amplia bodega de 8.5 m².',
    ciudad: 'Manizales',
    barrio_sector: 'San Vicente',
    tipo_operacion: 'venta',
    tipo_propiedad: 'apartamento',
    precio: 330000000,
    es_negociable: false,
    area_construida: 57,
    habitaciones: 2,
    banos_completos: 2,
    parqueaderos: 1,
    tiene_balcon: false,
    tiene_gimnasio: false,
    tiene_piscina_comun: true,
    tiene_ascensor: true,
    tiene_porteria_24h: true,
    imagenes: [
      { id: 'img-tsv1', url_imagen: 'https://images.pexels.com/photos/1105754/pexels-photo-1105754.jpeg', es_principal: true },
      { id: 'img-tsv2', url_imagen: 'https://images.pexels.com/photos/176390/pexels-photo-176390.jpeg', es_principal: false },
    ],
    es_destacado: false,
    estado_publicacion: 'publicado',
    fecha_publicacion: new Date().toISOString(),
  },
  {
    id: 'prop-apartaestudio-palermo',
    titulo: 'Apartaestudio en Venta en Abudhabi, Palermo',
    descripcion: 'Acogedor apartaestudio de 3 ambientes en el sector de Palermo. Ubicado en un piso 4, cuenta con parqueadero privado, depósito y ascensor. Ideal para inversión o para vivir.',
    ciudad: 'Manizales',
    barrio_sector: 'Palermo',
    tipo_operacion: 'venta',
    tipo_propiedad: 'apartamento',
    precio: 180000000,
    es_negociable: false,
    area_construida: 44,
    habitaciones: 1,
    banos_completos: 1,
    parqueaderos: 1,
    tiene_balcon: false,
    tiene_gimnasio: false,
    tiene_piscina_comun: false,
    tiene_ascensor: true,
    tiene_porteria_24h: true,
    imagenes: [
      { id: 'img-ap1', url_imagen: 'https://images.pexels.com/photos/545045/pexels-photo-545045.jpeg', es_principal: true },
      { id: 'img-ap2', url_imagen: 'https://images.pexels.com/photos/209291/pexels-photo-209291.jpeg', es_principal: false },
    ],
    es_destacado: false,
    estado_publicacion: 'publicado',
    fecha_publicacion: new Date().toISOString(),
  }
];

export const CHATBOT_KNOWLEDGE_BASE = [
    {
        keywords: ['hola', 'buenos', 'buenas'],
        answer: '¡Hola! Soy Aura, tu asistente virtual de Osorio & León Group. ¿Cómo puedo ayudarte hoy? Puedes preguntarme sobre nuestros servicios, horarios o cómo contactarnos.'
    },
    {
        keywords: ['servicios', 'ayudan', 'hacen'],
        answer: 'Ofrecemos servicios de venta, arrendamiento, administración y avalúos de propiedades. ¿Te gustaría saber más sobre alguno en particular?'
    },
    {
        keywords: ['horario', 'atienden', 'abren'],
        answer: `Nuestro horario de atención es de Lunes a Viernes, de 9:00 AM a 6:00 PM. ¡Estaremos encantados de atenderte!`
    },
    {
        keywords: ['contacto', 'teléfono', 'llamar', 'dirección', 'email'],
        answer: `Claro, puedes contactarnos a los teléfonos ${COMPANY_INFO.phones[0]} o ${COMPANY_INFO.phones[1]}. Nuestra oficina se encuentra en ${COMPANY_INFO.address}. Para una atención más directa, te recomiendo usar el botón de WhatsApp.`
    },
    {
        keywords: ['vender', 'venda', 'propiedad'],
        answer: '¡Excelente! Para vender tu propiedad, el primer paso es contactar a uno de nuestros asesores para una valoración. Puedes iniciar el proceso a través de nuestro WhatsApp.'
    },
    {
        keywords: ['arrendar', 'arriendo', 'alquilar'],
        answer: 'Si buscas una propiedad para arrendar, puedes usar los filtros en nuestra página para ver las opciones disponibles. Si quieres que te ayudemos a arrendar tu propiedad, contáctanos por WhatsApp.'
    },
    {
        keywords: ['gracias', 'ok', 'listo'],
        answer: '¡Con mucho gusto! Si tienes alguna otra pregunta, no dudes en consultarme. Para una asesoría personalizada, te invito a contactarnos por WhatsApp.'
    }
];