

import type { Property, Testimonial } from './types';

export const COMPANY_INFO = {
  name: 'Osorio & León Group S.A.S',
  sloganKey: 'company.slogan',
  logoUrl: 'https://lh3.googleusercontent.com/pw/AP1GczPVONrjfngMlSIYlLwGZZDIvf4Pg4B2bslt8wiiKOb2zg2Eay0bE93XxfLPlc0TShZzDAKzJ1fe9lIBIODXFeYNUtrn3oBds3GkFZHU1KUWo6xHp9yR_3VuU4zXWRebD4A1NFS7YumdjiBdVuUyKG8=w500-h500-s-no-gm',
  address: 'Manizales, Caldas, Colombia',
  registrationNumber: 'Matricula Arrendador S-MAT-SINT-USC 2025-7',
  phones: ['+57 311 567 3740', '+57 321 278 0607'],
  email: 'osorioyleongroupdigital@gmail.com',
  hoursKey: 'company.hours',
  missionKey: 'company.mission',
  visionKey: 'company.vision',
  values: [
    { nameKey: 'values.commitment.name', descriptionKey: 'values.commitment.description' },
    { nameKey: 'values.transparency.name', descriptionKey: 'values.transparency.description' },
    { nameKey: 'values.professionalism.name', descriptionKey: 'values.professionalism.description' },
    { nameKey: 'values.collaboration.name', descriptionKey: 'values.collaboration.description' },
    { nameKey: 'values.innovation.name', descriptionKey: 'values.innovation.description' },
  ],
};

export const SOCIAL_LINKS: { [key: string]: string } = {
  whatsapp1: 'https://wa.me/573115673740',
  whatsapp2: 'https://wa.me/573212780607',
  facebook: 'https://www.facebook.com/inmobiliariaenmanizales',
  instagram: 'https://www.instagram.com/osorioyleongroup',
  youtube: 'https://www.youtube.com/@OSORIOYLEONGROUP',
  tiktok: 'https://www.tiktok.com/@osorioyleongroup',
  reviews: 'https://g.page/r/CXOeo9LDDy8BEBM/review',
  googleMaps: "https://www.google.com/maps/place/5%C2%B003'31.3%22N+75%C2%B029'15.3%22W/@5.0586957,-75.488227,19z/data=!3m1!4b1!4m4!3m3!8m2!3d5.0586944!4d-75.4875833?entry=ttu&g_ep=EgoyMDI1MDkyOS4wIKXMDSoASAFQAw%3D%3D",
};

export const ADMIN_CREDENTIALS = {
  user: 'osorioyleongroup@gmail.com',
  pass: 'Contraseña123',
};

export const MOCK_PROPERTIES: Property[] = [
    {
      id: 'venta-casa-sanrafael-1',
      titulo: 'Casa en Venta en Conjunto Cerrado - San Rafael',
      descripcion: 'Excelente oportunidad de inversión en el prestigioso sector de San Rafael. Esta casa de 130 m² se encuentra en un tranquilo conjunto cerrado, ofreciendo máxima seguridad. Cuenta con 3 amplias habitaciones (la principal con vestier y baño privado), 3 baños, una moderna cocina integral recientemente remodelada con estufa de vidrio templado, y un acogedor patio interno. El garaje privado incluye puerta eléctrica y cámara de seguridad. Ideal para inversores, la propiedad ya se encuentra rentada generando $2.300.000 mensuales.',
      departamento: 'Caldas',
      ciudad: 'Manizales',
      barrio_sector: 'San Rafael',
      direccion_completa: 'Cra 22 #72-50 Casa 8',
      estrato: 5,
      tipo_operacion: 'venta',
      tipo_propiedad: 'casa',
      precio: 480000000,
      valor_administracion: 100000,
      es_negociable: false, 
      area_construida: 130,
      habitaciones: 3,
      banos_completos: 3,
      parqueaderos: 1,
      estado_inmueble: 'remodeled',
      estado_amoblado: 'sin_amoblar',
      tiene_balcon: false,
      tiene_gimnasio: false,
      tiene_piscina_comun: false,
      tiene_ascensor: false,
      tiene_porteria_24h: true,
      tiene_zonas_verdes: true,
      tiene_cancha_futbol: false,
      tiene_kiosko_asados: false,
      tiene_salon_social: false,
      tiene_juegos_infantiles: false,
      tiene_sendero_peatonal: false,
      imagenes: [
        { id: 'img-vsr1', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczO-hQBLShw_zxQxeCwwLfEgJDs8Wzb2RskOt93G6VrachD7hih5xp9LmoyhoK5KZhR2r5SW4rdIlfsbPhOnmkYR8Sv3cXT2oCudlI0zbqCDqY2_68TWtzPoVUJ_0xyIKFAYdynerWhdjk4Ld3trJaJo=w743-h991-s-no-gm?authuser=0', es_principal: true, alt_text: 'Fachada de la casa en San Rafael' },
        { id: 'img-vsr2', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczOhNsnFIgFTUrzbBgKdWgl4vCaQTDsWrK7SE1jMk-EmWPwQeL94MC3scsZ8ZrO4ejfvq15OMVCFhQKRMuQjqzWJLOGA6ZKRGh4oz01wjlddZQAV_vNqzLiMA5PNrGAIk8CBO1oRhbl77Qk5_dWyiIxr=w743-h991-s-no-gm?authuser=0', es_principal: false, alt_text: 'Cocina integral remodelada con acabados modernos' },
        { id: 'img-vsr3', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczPoj-IY5uk980E0NH8u5WfJTdd1wbJqaJ_Ss6fHHOYLc0Criw-y1vjSOvcl5jXff9-EPjdANV-azIM_FGKBDjSt4kDYcZk55VR10SQDoZPNE9D8Ricwa47Tmayhp3uWrbE1xuGFgA8xvJfIX1eun60p=w743-h991-s-no-gm?authuser=0', es_principal: false, alt_text: 'Sala de estar espaciosa y luminosa' },
        { id: 'img-vsr4', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczPqgVkyZF3LcY6nZt0IgvmtBMSQPjnelB9uD52-4KBxKPzSpk-omequ6LCL00_Mh3CykzZd8ms_WeC_TY_XvNpkRN-MbhdeV7SDRnPYtI7wEVcJH18j74BiOrQvtQWwoa4tgxj8Q2GIbV4KeG5cTcRV=w743-h991-s-no-gm?authuser=0', es_principal: false, alt_text: 'Habitación principal con vestier' },
        { id: 'img-vsr5', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczMA25k8AaQcPdlEk9dQup4vpN1-FRkDA-Op6iMrVd1iCSBIqpjdgP8LvnW_iMzdSCGk1Sv2zfh-AxHzGJGoy4YEb8aQOcgQ94lhNO6OS5hsvf7syMbgfe8aq5LXAFjH20jCngYogIyLR5cD-2ewakF3=w743-h991-s-no-gm?authuser=0', es_principal: false, alt_text: 'Baño moderno y remodelado' },
        { id: 'img-vsr6', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczMYOGMXaoKbHx1JBrzFEL8daoELj4C2yQhThMMDtPuQPz1EmTJ8Dg_2Olb90IubLL1yQuS14F5EXCR2Yn3G0hWuyFuWJUdHl_3baUgmuZkhzOfz0bgUy1mL6dcOHqv_AqNmnMkRvDhxb90alg9pUiVa=w743-h991-s-no-gm?authuser=0', es_principal: false, alt_text: 'Patio interno privado y acogedor' },
        { id: 'img-vsr1', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczMm5-IJ2ZASJDwUdt5I2mDwoI2b_--J_lMl-5_X5GkUwH4KQLispC5mg5_83_ATRoXNuPPNSR63al-RZ9vyZ-sXqGj0wi_9Au_k8DnP3ZmoaG9uE0x86PGuR1xiARe6-l7yHaHOFRV_MevRUcLJaemZ=w743-h991-s-no-gm?authuser=0', es_principal: true, alt_text: 'Fachada de la casa en San Rafael' },
        { id: 'img-vsr2', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczPXxHgj1_66_q0hn9LG8Ov08VNNlmhkx0sxkaShgwKyZg-PY1rSLUqdehbyPixiOvCjIB9uaJzHdyJcatfuxLvCa7M4MQR7_PI3sci-Y03jIVbnnflSxY5t4KDLzVxKxxc0OIKw1rdnlTYJyVrR58OS=w743-h991-s-no-gm?authuser=0', es_principal: false, alt_text: 'Cocina integral remodelada con acabados modernos' },
        { id: 'img-vsr3', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczMFQ39ESWv4J9Wdvmp2BmlImH64mwZGhEAhtEcY7D-8tec_icCVUTcrAWTQqvxRb6x9ACagV3sxWIiF0wygUENaVrluLyN7Uf4Ie5kuw_gnl8SEoSzDbZQ2Zb74PYCAdDGYzmWTWvRB-e5LpuA1W16k=w743-h991-s-no-gm?authuser=0', es_principal: false, alt_text: 'Sala de estar espaciosa y luminosa' },
        { id: 'img-vsr4', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczN86CK1vqZf2hpVlpk3V0yW35Ke79a0OJWKxBh1OoREDDjxoSmyf4npe3x4OpqDQRJ-5LYlfpLCpz4hhD9mVOIhjZnezdKMUe_S3OJ9KgjW3IRo0h70GInTA6vTIKxsDj7Y6dUHczSkbqc8RpJihBNM=w743-h991-s-no-gm?authuser=0', es_principal: false, alt_text: 'Habitación principal con vestier' },
        { id: 'img-vsr5', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczO2QVMWkVpvcKC2IMo6rPSS1Qszf0ZPcIfO4SjL3v6I91WUNVsZyQx5CR1UEM5dle7D3k08Lelw0orB2b_hjj8r1iLFCTE5uo84bLIB4NAxWYCfIx1CtOat7bZWdmWHs2nwE1FIUlVLUUp6oTa1fs6s=w743-h991-s-no-gm?authuser=0', es_principal: false, alt_text: 'Baño moderno y remodelado' },
        { id: 'img-vsr6', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczNnaIlyNXlO4PbE0FGKdfpRkS69VK7DCeiyaBAfW_UhAAg5rw7ywLnI48JP2WLJvoLLbQZ2Uy9ihzmUUWbhp-es-HpCQJsps4I96mFuGFwc2VKcShgs3AqNZpARMsWccHKSLFUAo4rAXGmMcU-sdxXK=w743-h991-s-no-gm?authuser=0', es_principal: false, alt_text: 'Patio interno privado y acogedor' },
        { id: 'img-vsr1', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczNsnVr43BJHDMABR4VmxXsyCF_-qDdnsnc1HHa-N3WAEgK6rgTHljOKT_3DzNME1HfYxIcaoku47Fe084Uv-BpjJR-gQqnjHt2xx5l8DHE-C9G3HQAwOsYxYG0oovPW0FwSHKGghcfr92leNLuM8fVz=w743-h991-s-no-gm?authuser=0', es_principal: true, alt_text: 'Fachada de la casa en San Rafael' },
        { id: 'img-vsr2', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczMzFqcb8lVNo7XuMbXHxVr8ow3gm7ixKVxSACQesBn7KLAWoDPZqsS1BAl4wnbLu1IZG8uEGx89ghApRFrbrWdfd8e-_pb9xkVWB5l3tQhlPcNuHlqPhlO-Xl4VtbrdPtAmrDffDh6jZ8bi1BH5mSoX=w743-h991-s-no-gm?authuser=0', es_principal: false, alt_text: 'Cocina integral remodelada con acabados modernos' },
        { id: 'img-vsr3', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczOsUPJknkk_IcAC58eRF6z_YCKYVQohgZ93RxjwwYmJv7Xuh623XfUvL4CQMBCdpkHZBYLFTqhL5BT7nrcNrvFX8YtgvMUPMHMdEMUk3k9j4MWMOyk1-V69OBE6oyBJbJxXOX72oyIJptEBHAB0NTe-=w743-h991-s-no-gm?authuser=0', es_principal: false, alt_text: 'Sala de estar espaciosa y luminosa' },
        { id: 'img-vsr4', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczPOw0xIW4sjcZ7VLCkQZ6W62qg2tIb57NS3RJr7bmrU1jvJ03ELQ1mMqcNsedL7KSNSTCmDCGKtzIRNIOb2Px_vbRlvn_vT-E5orScQN4h06CWPnQM7cVXsuGp1nBPsmBfgBj_MWv-A0ZovunwieD0h=w743-h991-s-no-gm?authuser=0', es_principal: false, alt_text: 'Habitación principal con vestier' },
        { id: 'img-vsr5', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczPsmVX3hOW1n_SbfeCWKVxATN5-OoPeZ5S3q8j2xfpj6iE_5YlSlcaGNMgBAgYLHcecuT7fOeI-Rw49_AiY_825OsAaQza9dV0irsp4320O4QoqzeCcZpxXVY7kGFhoTNnmHFcC-25QkiA7Tu0r2opi=w743-h991-s-no-gm?authuser=0', es_principal: false, alt_text: 'Baño moderno y remodelado' },
      ],
      es_destacado: false,
      estado_publicacion: 'publicado',
      fecha_publicacion: new Date().toISOString(),
    },
    {
      id: 'venta-casa-miradorlomas-1',
      titulo: 'Casa en Venta en Conjunto Mirador de las Lomas, Villamaría',
      descripcion: 'Casa de doble esquina en la vía principal del conjunto cerrado Mirador de las Lomas. En la segunda planta cuenta con alcoba principal con baño privado y vestier, 2 alcobas adicionales con clóset, y un baño completo. Incluye estudio completo con mueble. La planta baja tiene baño social, sala de estar, sala principal-comedor, barra americana, cocina integral, despensa y bodega. Pisos de cerámica en el primer piso y madera flotante en el segundo. Se entrega con cortinas en panel japonés y blackout. Adicionalmente, incluye un lote contiguo de 27m² con patio de ropas cubierto con pérgola, clóset, pisos en porcelanato y puerta de garaje eléctrica.',
      departamento: 'Caldas',
      ciudad: 'Villamaría',
      barrio_sector: 'Mirador de las Lomas',
      tipo_operacion: 'venta',
      tipo_propiedad: 'casa',
      precio: 520000000,
      valor_administracion: 65700,
      es_negociable: true,
      area_construida: 149,
      habitaciones: 3,
      banos_completos: 3,
      parqueaderos: 1,
      estado_inmueble: 'used',
      estado_amoblado: 'sin_amoblar',
      tiene_balcon: false,
      tiene_gimnasio: false,
      tiene_piscina_comun: false,
      tiene_ascensor: false,
      tiene_porteria_24h: true,
      tiene_zonas_verdes: true,
      tiene_cancha_futbol: false,
      tiene_kiosko_asados: false,
      tiene_salon_social: false,
      tiene_juegos_infantiles: false,
      tiene_sendero_peatonal: false,
      imagenes: [
        { id: 'img-vml1', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczPuj9o4-OYhqa-dBfb6YeDSP9OJC7S5_-qTCH3eunavy1mrfztSljF1xMeV2C7_q152UwR7Gz3jNt1ybfDjQDna4Qp03khi4JDqBHyzW-_BAVjmWpwJywVcB8xYFOROvvoK77lMWSrVJXPvRnyFWZnf=w1024-h768-s-no-gm?authuser=0', es_principal: true, alt_text: 'Fachada de la casa esquinera en Mirador de las Lomas' },
        { id: 'img-vml2', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczOl6Y4CxQnD9KYSWVNSf-2cfamr_UMcGTUsej1S4iKLsvMsiQmpEf_NA_X3XkzUcSwWJ5qqa7-ZaT1p2O60UM63ZcNqeV-nza4qrYecaSIU21FHieMAf4zwqR95W74_4KSKzWwiFYhMf6i6JocmmiM9=w816-h512-s-no-gm?authuser=0', es_principal: false, alt_text: 'Sala principal y comedor con pisos de cerámica' },
        { id: 'img-vml3', url_imagen: 'https://photos.google.com/share/AF1QipM6VnwzcrNqdp6F5x1wa_BTuQZWI4ameZwGe9Ra597N9GddG18BBEipfe6HELIGYw/photo/AF1QipNZe48UYIqOJYGklsMKeaMmxMPy3iTdwjtht2xK?key=clIwdEhtQ3YtWm9XcWZEcmxXZng3OVdrdER3YjNB', es_principal: false, alt_text: 'Cocina integral con barra americana' },
        { id: 'img-vml4', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczMgl0Bh4aEl7RlHhtKyj5G4Im4rYvaBudMmNQNLdeuoJjjqwBAbNyoEWiWBTBaZT7r1BAofxqK4hD1F00s4cDkfhC3_8t3iJdv2Xmsmr_bpeFXw1bG3iJDvOOT3tJpkdBGnSTVcWDMRvpuk-9Cw_aRR=w743-h991-s-no-gm?authuser=0', es_principal: false, alt_text: 'Estudio completo con mueble incluido' },
        { id: 'img-vml5', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczNkbsJfGovLTLqwXro2Yui04dsqEPP34q7sPtRknCWRwNigV1cmgUCYoWx5eiq5pozUbqX6MbscB3W_Xnr9khJS8SCIq3hKd_GtBznlZRqStDDQscBvnvwkRG7dw5J6ikXw2nu3SNgts5qv2XIIEmUY=w743-h991-s-no-gm?authuser=0', es_principal: false, alt_text: 'Habitación en segunda planta con piso de madera flotante' },
        { id: 'img-vml6', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczMq_HdGxjkFdj67rwWiDJpOQnJKj3_2YcP15z7OGCGC62U1jQooV2g3JiBb1oguiO7eQSGmckHvvqq6MU0reo7ws1VTP6mB06Uc_XaRjGxgiI_6MZW29daBVCefVqPZzdvL57oxGc3BDyTWa8SSdHgz=w1024-h768-s-no-gm?authuser=0', es_principal: false, alt_text: 'Patio cubierto con pérgola de policarbonato' },
        { id: 'img-vml7', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczOUgSvkLJYO0z8_SBJMblHss5Dl6HaHjUsHTPM9nkOyVziD2fx45fUH1QKQyaWhBef6ubTrX-mp3kQbiHG8GRQxS1cOvzDwkthlsjtRsyon_yYwwewy-CgqYck-JoLnCynbxubRSXqb9U44DUELBhDF=w743-h991-s-no-gm?authuser=0', es_principal: false, alt_text: 'Baño moderno y completo' },
        { id: 'img-vml1', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczNP5eItNCFdu8aH3HhaDFFAEGhXzpYrLmMG2q4F0VmafZzXiek61fjEOYj6lAoVZ6ykTIe5HEU3jsN8JKDlKjsyHg1z4LjH_l76EYTd9o4tfIoS1jZ9sBohCZ5L490m0HcQIEnzbLGZVZwqY_RXJ9Ak=w1024-h768-s-no-gm?authuser=0', es_principal: true, alt_text: 'Fachada de la casa esquinera en Mirador de las Lomas' },
        { id: 'img-vml2', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczP7XsVnQyW8LBvWGDaVUA6FSbELALtCX2GQl5TufpSw1t8LhZVXgJiENsHCj9HPCBliy_drajBvHs4oWKHW33yg3Y3dGheZBlCZz1ZekrwnbON80pKxTZbNOQ0zmLpQgX2aqDlwgOiwuxoPhMZz921C=w1024-h768-s-no-gm?authuser=0', es_principal: false, alt_text: 'Sala principal y comedor con pisos de cerámica' },
        { id: 'img-vml3', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczOmWmkqktJBadMP2QlNQng9lMtv8KAMJcXEkv0zg4tdhjzqPefHBO2X2wp1rXuEIuE1WeeKehm5vwb7myPzQTtNsEvxfhYOZ4sTbKx0OkRG5BthhqHCtiqCtRgASenQveCObEI6C5oYe9c253LLMZrc=w743-h991-s-no-gm?authuser=0', es_principal: false, alt_text: 'Cocina integral con barra americana' },
        { id: 'img-vml4', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczPY9X_WxiyHNNLP-PYgeEfq9sPx0CD93UUeJc3SY-ZdA7zBcHleHtzHQ4pe5BOpZ37wqSEgoS3djfrKzfS4fW0axHyZhlGplaEfzpHUINOGdkaqy2oVLzpCGjf6HVci6FSt5CUwWG4CPNC436AnyHGb=w743-h991-s-no-gm?authuser=0', es_principal: false, alt_text: 'Estudio completo con mueble incluido' },
        { id: 'img-vml5', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczPNnLqFq27BqrFMXPIjd7rson7smoPAxQfGdVogU6xfAOBRC9YiXlmoDQjN9yNHnng3ENuPZnvYFYaAXIsi8TiG2qZSih7v5VVkXdAT6OpjqH_OKZ1rRozEGHaUwcZha26ElzrtNF7yBttq7ck9IAPG=w1024-h768-s-no-gm?authuser=0', es_principal: false, alt_text: 'Habitación en segunda planta con piso de madera flotante' },
        { id: 'img-vml6', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczOfgGeA3S9QAJjy5fCGtKKqzrm6rytZURU146etqp6-90SmWNh_XWz8T3wS57DRsy7HBF3CJtZviL_2FwiB7cLg_CHNXcR_NX1KeM8Ya-v2pNbxgw7_ASkKCWEZsEKldtOM_Ylo9xnmxnqvB1ecpp-f=w743-h991-s-no-gm?authuser=0', es_principal: false, alt_text: 'Patio cubierto con pérgola de policarbonato' },
        { id: 'img-vml7', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczNsmxyu0FZKL_WieE00mEf2i8DhCBxTYHHThr4IPqssbIIqR1gKsfQ4f2aEPtyME3yfkjiAb1SmdWxXCNIDPU2v7cTx3LQnWa1vX3_-P-lEDibnDKacn-uLPdEi1UK9tojcjEqwdsyqBRwkhZjxE9lj=w812-h991-s-no-gm?authuser=0', es_principal: false, alt_text: 'Baño moderno y completo' },
        { id: 'img-vml7', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczMEvaYw_pipwqbLQ4qyXQtocV6BjuCq6tm2Lh4HiWWVMWJ6K1WYmidVZIptaeMcA6nXkJW5UgdcqmDTl0ZXufsg3JW_r_oDNxm5g07PtuKa_45-gZTHPdkRnsp787PInCwUckJwcBfJ_AjT-84OXTnc=w743-h991-s-no-gm?authuser=0', es_principal: false, alt_text: 'Baño moderno y completo' },
      ],
      es_destacado: false,
      estado_publicacion: 'publicado',
      fecha_publicacion: new Date().toISOString(),
    },
    // Propiedades en Venta
    {
      id: 'venta-casa-conjunto-1',
      titulo: 'CASA BOSQUES DE LA SIERRA',
      descripcion: 'Espectacular casa en venta con pérgola privada de 18 m². Cuenta con 3 habitaciones, 3.5 baños, estudio y cuarto de servicio. El conjunto residencial ofrece zonas verdes, cancha de fútbol, kiosko para asados y fogatas, salón social, juegos y sendero peatonal.',
      departamento: 'Caldas',
      ciudad: 'Manizales',
      barrio_sector: 'Conjunto Residencial',
      estrato: 6,
      tipo_operacion: 'venta',
      tipo_propiedad: 'casa',
      precio: 850000000,
      valor_administracion: 504000,
      es_negociable: false,
      area_construida: 145,
      habitaciones: 3,
      banos_completos: 3,
      parqueaderos: 2,
      estado_inmueble: 'used',
      estado_amoblado: 'sin_amoblar',
      tiene_balcon: false,
      tiene_gimnasio: false,
      tiene_piscina_comun: false,
      tiene_ascensor: false,
      tiene_porteria_24h: true,
      tiene_zonas_verdes: true,
      tiene_cancha_futbol: true,
      tiene_kiosko_asados: true,
      tiene_salon_social: true,
      tiene_juegos_infantiles: true,
      tiene_sendero_peatonal: true,
      imagenes: [
        { id: 'img-vc1', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczOF5_IKzkceoEz9msBp7abLnrRRijQb6oMHQm6q5rA8Pwgx4tRQ2FFdW_yU0NMMxMrrfS64l4AYNc0dPJc4CjckinTUIHlNT69SRhQcUPutERs2EWo5F1GaKmDeUe1c5Ehd7MKh7O-s8UkLpqWH06Zb=w1260-h945-s-no-gm?authuser=0', es_principal: true },
        { id: 'img-vc2', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczOfDrqUzW84waEcQbxQ0yszGLkMC3pD_ZJXT2CrS_ShurEI2MAWdjuJ_nEHf5SctqpZVtfHty7wQFdDr2vSZqDk_YyXPHKJWqHYb1qA5VsutUKVqvX-pceTUmpyy4M-XBeTR3O5a4YnIYdzlR51mgrh=w1260-h945-s-no-gm?authuser=0', es_principal: false },
        { id: 'img-vc3', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczP5HSEEbh3CO7pDLKCE40ldh1XQbpxnsQ9IYd8gS-Y0fG07mtJo18bLfQHTA1cD9VggOJqPtO2VaFWrm2UqeQIRBcz152Yw0mdAMzAaA7pnZmSgwJQ-DRxE0PE3_cnON2JVDfKVYcKUcpjqyLnPQXqh=w1260-h945-s-no-gm?authuser=0', es_principal: false },
        { id: 'img-vc1', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczN5vJ4hB-R543u-WDTTEEZUMX5NH2qjzH7FbYR0aoOfYjuMUDfhyxhqzMuKY-nZXVqOXg7kSVbJ4QD3rr3WcmSNVOI0e7wjJFy3cOn4gAaxrz-XUq_Yiv0iMQQ33_1T4HdbTW9xT-3Tsq1WCwBsStP7=w1260-h945-s-no-gm?authuser=0', es_principal: true },
        { id: 'img-vc2', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczPvsoaZT3I2WPmUmdf8BTno60-AR9PBEus2u5ugom6J-eNLWu-H3sEolF5remA2Itb1xW3vS8gzruDEH4N9Wb7ys7wYPpYvBkPPRkd-FGw1O9DGeybKDcSBNjwx8B9-h6kDLveREupOr5LrzXP9oXBl=w1260-h945-s-no-gm?authuser=0', es_principal: false },
        { id: 'img-vc3', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczMHcXnUCnR5wefQU3VqSSsno4YMALPhNs0JerzKJGEEziuiHEcFJEnWIZ5u9GloYuGt1FMEw3sFwTtHSohE0IZF0Pu7Pite-QXxDJ1RQKomew9Slg4tlv24rB5fsPr99plrH6E-akMYzCLaLGqctRis=w1260-h945-s-no-gm?authuser=0', es_principal: false },
        { id: 'img-vc1', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczPALp5utrWj7ug7cEP-SgjANxBFZvEvXEyG-1p023dzJ1G-BSUPfJgSHdGO0YFeQvdSn14j2nI7HodbUtDh5Tg5BzXl5Fj2wUn2aWzhpphkARQUtYJUCsTDPElozcaKRGb3SDPAEEw4tSbFk2I7VXR8=w1260-h945-s-no-gm?authuser=0', es_principal: true },
        { id: 'img-vc2', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczPInnnhxva6mK3j5YLiy9vgWvNh5p0S3elcChPnucjwvQilergezd9pI4_qm4d08-s73m1a3TNRhhS_G-jXo7-tltBHG1ZGGYK5OwJjFtLs15ZlTLMx79ElaLbKvwYHcMZQRRI1OCVY-uu2Mw6nEkgI=w1260-h945-s-no-gm?authuser=0', es_principal: false },
        { id: 'img-vc3', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczPy_xXgPOTv54Up0v2rZpNt2O4mQJEhmoTnhVGGgp2I-vXyRbBmAjKtP7NRcu4Xtw7t_x3AMnZwrm0D7XZKlIzJmW_MNxGzIgGPXvxgIikEqjxyotaHUorTE6t4SF-ZME462fQivNOjsBcqWUKySqcg=w1260-h945-s-no-gm?authuser=0', es_principal: false },
        { id: 'img-vc1', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczOLGTpfdmyiso4KHuH7wzf_EBR_Fn5l8EHZTQIiihBnv3UnVgJnatuyncXoK28WiFS2svipUBceWTzZxT9alr9Drmb5MjtdxJEPyVCrdXrysfYOG1iQQaHaXq_Vdny6iN-2G6AFJ1hEdPfmOZxPzXLl=w1260-h945-s-no-gm?authuser=0', es_principal: true },
        { id: 'img-vc2', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczNSTTbSXOhmQ_gxwJTtYtPCsQelU1ccW8v1fUZEA9KyzaeJp90hXSd2ysk14KgWg6_DdXRxydpAKwvTBfwwMbBJjRPG5mft-82HncXmjgHTAJxF54CInO4lMZubCwEIZULR0SBZ-g3n8uXtfyElCtji=w1260-h945-s-no-gm?authuser=0', es_principal: false },
        { id: 'img-vc3', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczPVKQXCj4E0ElZxhRE_D1IVr96UStvHIq4vTf-oBa9wOPP-AaedYWgyKxYTwj5Ts_Kh7umpS52jRZrTuKLLDuuIT3tOZvBx4yLFPz0ULD-WKF3eywF3Z7-AV4k9jODV6Jn5qpPLGUfz_LxNbOS-d0zg=w1260-h945-s-no-gm?authuser=0', es_principal: false },
        { id: 'img-vc1', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczOyyksbMWlhM1jSAcdS9Nmwnn--CzEs5GoQT5-HrbyWNi_sU_vatazBNLexvqtqf8kdJ-hFtJTCD3v2_U9f3nDXzTmGYHYWOmsnn9Ego6KOgez9uWXIpcmlR0PSkn39-JNOH_2KcVblG6h1E6Cxbb3q=w709-h945-s-no-gm?authuser=0', es_principal: true },
        { id: 'img-vc2', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczOhQIiSJg6SnDgE05JU-umjB2bdN7_8WHapBFu1wlMhK0pdurFvx4nIZB7gz5-1QKy4MKPcumgGPauIFuhKC8tUGWypTTxGq-LehkRLZpNan05fCAUIBPX07PtGIYy2F-xRU29Z3c-Oe1I9ObNpi7wI=w1260-h945-s-no-gm?authuser=0', es_principal: false },
        { id: 'img-vc3', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczOMkmNH_b67kBv-JBb7HpcsHe-S5vLH-ux2u9JIDXf-6iFS5WtZsSYm3IFiFmE4HXQk8A-hPFJ9EX4_Roo6erm4MTqAWYypUUDqBhhAljofXLFui8XVPscWWVHEhRVjY7ZrcBX1Qk8hsSHKMA18yXAd=w1260-h945-s-no-gm?authuser=0', es_principal: false },
      ],
      es_destacado: false,
      estado_publicacion: 'publicado',
      fecha_publicacion: new Date().toISOString(),
    },
    {
      id: 'venta-apt-sanvicente',
      titulo: 'Apartamento en Venta en Torres de San Vicente',
      descripcion: "Apartamento en venta en Torres de San Vicente (Estrato 4). Incluye bodega. El conjunto cuenta con excelentes áreas sociales: piscina para adultos y niños, cancha múltiple, salón social y terraza, zona BBQ, juegos infantiles, lobby y ascensores.",
      departamento: 'Caldas',
      ciudad: 'Manizales',
      barrio_sector: 'Torres de San Vicente',
      estrato: 4,
      tipo_operacion: 'venta',
      tipo_propiedad: 'apartamento',
      precio: 330000000,
      valor_administracion: 270000,
      es_negociable: false,
      area_construida: 57,
      habitaciones: 2,
      banos_completos: 2,
      parqueaderos: 1,
      estado_inmueble: 'used',
      estado_amoblado: 'sin_amoblar',
      tiene_balcon: true, // Por la terraza
      tiene_gimnasio: false,
      tiene_piscina_comun: true,
      tiene_ascensor: true,
      tiene_porteria_24h: true,
      tiene_zonas_verdes: true,
      tiene_cancha_futbol: true,
      tiene_kiosko_asados: true,
      tiene_salon_social: true,
      tiene_juegos_infantiles: true,
      tiene_sendero_peatonal: false,
      imagenes: [
        { id: 'img-vc1', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczOf6nOwU5jvlgsbaU056BdDgFlJh_yF5KWzOTLLxYNjA9aOX4WREpvX9HC1ZgSCZA0fACZr1hyXRwaL9TQ6D6ARlC_Z2DFRh4m6V4ebRClPM1FAgzubgPSf7NnKkrGVO_jPtMRXftClgxk8VPjbqqMx=w958-h600-s-no-gm?authuser=0', es_principal: true },
        { id: 'img-vc2', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczNsGBWo_abvMUhjhclZv_jeKfKHpLRA4bnIJwI42foVwcYNFim0np-G0mMolne8A6Xw39UJyoAookzrYjXjEie0OSaMizXvoET7VTwheGZGrXzYN-ps_NHjiVyZr2lyrGHz0FdI7lYffsmOJGbTZjT1=w958-h539-s-no-gm?authuser=0', es_principal: false },
        { id: 'img-vc3', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczP9HyH5JxeTimlEqy_JxC_0HH2hA0dvWvAuF1fznrFLw-MQQxo4E3b42QDAYmi29weV8MLErqI017VJYezDQFf5jfkxxSPzV-TilXoeYxchkpaq_2mlyFkMG4v11rkctFc8OJ59gjh29-x-fxnFbdKF=w958-h539-s-no-gm?authuser=0', es_principal: false },
        { id: 'img-vc1', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczOfps6u3jUGSQV-dEtKb0xLxWn4z-qwCRYLNG0-ALk4b_LpFMUomgvrKXKE6_lXgFqrIhZhNll0K8z6LHSgDhO3Xo_ysBmL5ONfGR5o5D_QiOU9B5QLeTu2YgEjr7n_P7FXoPLNvy7jgg9040kS_agI=w531-h944-s-no-gm?authuser=0', es_principal: true },
        { id: 'img-vc2', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczPeoRxu-m4bJo5OPsSk795DAlDmMD3AXQtbmlxPfDr0Rdi-7zTZRQaz1hKBbZFSxeeYjDOM_YrTfcwtFHigi8cj9xeg8HHdDIdu1fepVVzhyr81MnBNWg9ZPSr92TY3bQjx4poe7Sw5ssE5O5QwAMHy=w531-h944-s-no-gm?authuser=0', es_principal: false },
        { id: 'img-vc3', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczM8Oh67iGqgjteCe3-MhXzU4JibAo2jiBBvxG-OJQNJkBI9nw0Wjsn5l__zNY18ko76M9pFVe_wY5QqAv7G0UgF_68jSMVxFPCv8C1CbIaTOcM2hAXrxKyA5QMSMMXUGwtEzVQKkwRcbPmkZJ-9WSRL=w531-h944-s-no-gm?authuser=0', es_principal: false },
        { id: 'img-vc1', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczM6Z2w_DjHyVK1RcMQgyGhw_DKJPZNRRAB-ewZJRTXsfUDWOn54HsI56fDGpZCIrSBPX2Q4MVdCf83VSG77yxoyn7S3puI4hhSIi2fPbYnPTvFKJzk_zPDKUr1AIPYz0sSUcqmDrcjztNW_xUZwDkfO=w958-h539-s-no-gm?authuser=0', es_principal: true },
        { id: 'img-vc2', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczPTspdD_hHsbJ1wrBCn9MdTdntDXnv5tyTrgknwbpLPhyPmA0IyVJ1C9NbhQNUIxpVDM0_qdX1c43WqH6W1R9fvDDf9J8lKD2uTN-1_K0UotKshyom1A9_dhfXSseOPvUBv-EoA8yxitKaBp4UR3iDv=w531-h944-s-no-gm?authuser=0', es_principal: false },
        { id: 'img-vc3', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczOGCXVHoIXxKxLzOrOriROuLm8qXVzCbeNec8kATq8wVfXULTXL2iOmC6nb6jpDg347kGr5xJ107LQl97xJ5tixYaRBbQ2dTIK43RMEPPQYPpcATk6gEGtSp-T-AgfP1KpHGoAAd5fHLeQm6fgKOsVm=w531-h944-s-no-gm?authuser=0', es_principal: false },
        { id: 'img-vc1', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczNQDqFBnFS2f-DSuxdeOl5a0R3UpwOTW217CF9UzLi8EGwdxb3e23U5FVopdCQObXpfXUr3sab4GetJTbVUWtptBTZVsksOrNAj5sHbHpXOTNahfOX4VMoTu4arPb150Y95uZBY35u32oePjwKzLxBQ=w531-h944-s-no-gm?authuser=0', es_principal: true },
        { id: 'img-vc2', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczOMUBvyEP0aOVWpgN_rXd0oDDoFMfhGk0Ls3UPFXWN00CDNxarIOe7FVN9RXmnDilkvfb6t-d5Lqn00G1LXCV0MepFKInE5gzyYOlQ6RCaOFtrIfwfK4Hl_RyQhXhGJ9MVdyirWnWZT0kWAVo_UTukZ=w958-h539-s-no-gm?authuser=0', es_principal: false },
        { id: 'img-vc3', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczMfX4j-QHUdoZ9nN-8AQd6eRUZUfpBO9aJ4fdJzVOGjNpHjt47U8jIbORtPFyC4wM2CkXNcIYplhaH_RpJao9_O5NIKMn2BI0MXY35oVlZerfnr7H7KOmagQL6EzwCsyG_kmiNIF0lX6kp7xYDTM5cZ=w375-h500-s-no-gm?authuser=0', es_principal: false },
        { id: 'img-vc3', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczPnFq7FvMeRU6tp4EFsS8dTOeTk9nK3DhGv6RN03zIOr7nvOaRe-qicOePthQKOtqilBpbQ4QG6xEXJo9I6hhWgAEkiSpqhDdINAfKMdNRMR4UYHUjZPFNtI8AC81EDpJpbzh_MuK8bJjGKO3jyhukG=w958-h539-s-no-gm?authuser=0', es_principal: false },
        { id: 'img-vc1', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczPzcQ8IziW85nooeGJs937pnfNmZWb7RM5DMzfpv6xOosUbYHfhn4c-alskr-kp-UjPYLMx9Axm2C35pNga9T4PNlFnzH_YWlEBMALe_a-_WymFR2GJLGr5zrrzB0ed2Wv08SsbL1Uro88NXUIKbrYk=w531-h944-s-no-gm?authuser=0', es_principal: true },
        { id: 'img-vc2', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczM5t1mgKOzJaQKoORUEJ3ZStV2uRIg87hwcxOusBeB48CDvE8fvFPPF66CfuwV2YVqcKi3N4PySCq5lCshb-6neqeNVRJIXDddZ7l4V8Bc0lm1w-EQ83VraqrtBCpQot-vssJrJPA8QMdOFWCPcU_2H=w955-h944-s-no-gm?authuser=0', es_principal: false },
        { id: 'img-vc3', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczPOYAPOl2Tf6k2Q4doIqMGfXiBXkb5c8YmihKFuIV9W-vsCe-RPBvZliUbth8m_hqRrS-U17mvrQ6lX5gXsueBQxVf-gF_3iseSGiBlVKsZ1fAOIaN4tdxnFxgFBgXWzDeoGeLiGG-NZJmeO0iAPi4z=w958-h539-s-no-gm?authuser=0', es_principal: false },
        { id: 'img-vc1', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczPBBxeoywuJywa_py5FsmPxas2KVO450Bc1eC58fXIxEHchiXiKa_R03YF-N3HP_jrFNZJ-416bA3EH2rt7SYhaJZtwdMohHNicmQXRKjqHytNSbFDwciPNXF0RCY9_6kte2El_CfropmPFJ77rlnvE=w531-h944-s-no-gm?authuser=0', es_principal: true },
        { id: 'img-vc2', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczMd10W2_-fuxSylvros15N96n5cVgFadzi4x6D-nYYHX_iWR9m_3ncCzgMbLilnd_OoJx3mcuIVNyFjSk0752MClOOgUZ0HrlpwKB2KVQFhz587cKp0nynnNZjeUJ4N6iFg45q38D8sD3wwTnCS3Eqe=w531-h944-s-no-gm?authuser=0', es_principal: false },
        { id: 'img-vc3', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczMMtRWfY1neLYYrTB8wN1fLJsV60BEEDh3bk3utkRp6oZx7JybTVIMYkNFie2AyrwaesaNJgSoHvq2EIcDBMcI-pEw1EYrUmWIWcqILcPo5baaK2dS7-G7uST3FEJaKtozX9F9fkI6zL6XNiyOgU3h4=w958-h539-s-no-gm?authuser=0', es_principal: false },
        { id: 'img-vc1', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczNamQb5uuD6H9WB8ATYg2SSF08hNP_LdYHoJja8qtXgW9dvZHJk_LEWOYWgLEW4GPUVROD4DaOH7c2wdut6KRVmjmMIMYdl4LyhpNG6lZMUCln-C18WWzBWm96TmyASGyvSdwdgNs_SKtIkV6horhab=w531-h944-s-no-gm?authuser=0', es_principal: true },
        { id: 'img-vc2', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczMjyFhOUtEIX7JsGw1bXXErDpePDq9HT0LdGopIosdQun6nyBZaDn0DlPk_EHLMWTeer51wp3YQifhcodLRMgRTwfq33kHjEYyfZfQ3PpPR5-bXSbHgq6z8ch33WHyeVVc-Mzu2p4ptg80EWthYficU=w958-h539-s-no-gm?authuser=0', es_principal: false },
        { id: 'img-vc3', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczO64Q3RY-m0K1_bNLQYRsPB-NwHMctEzpw-34Hqq_PpQ7_Xi5iW3KaEhotJUgxxKl-gy6ud1CIL8EjJk8e8_gz6CHanrhf6Y-GCWUuMPUhH3eZ_iX70fT3M--Fklv1blen_ybDFKE7b-6xQwCnbqGK4=w958-h539-s-no-gm?authuser=0', es_principal: false },
        { id: 'img-vc3', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczOzXShDSA_iqB9pbOuP67lV50KtC-PnxzGE88cUfdRDW-tgkQHNq689doe1BMwnGRgsEEiVCS3zws7mjpVcGbb0zAYh2J7vxdfjQuoOBRniyunPfgope9_UGZdXMXzz4HWot9R9rLgdOPrto9EQB4sq=w531-h944-s-no-gm?authuser=0', es_principal: false },
        { id: 'img-vc1', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczMGrGuvS_WbOD3sD67KSLkD0V9d3CjcH8jUBuZBPYSWFgGg-axIpDAZeO_qBETTdxrwuf2xdikETG16j0EzfdIg7ikPoy2aYgnwDAYRoR-5IjvsVXa16heSwRtWyhqCjKIEIKXNH9paLp4T78vEsvlO=w958-h539-s-no-gm?authuser=0', es_principal: true },
        { id: 'img-vc2', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczNHlrgQuA7rtrZ1LIp3wTwb7IjtAMdHfpMUfJlhumBmkwugcbVllBqpg9eVAmGAYx9ZhNjICGZSp9s7rQlUUO60yKCil7iSBVB0Rwjexts5ZR5KSS4V78TLu4n4F1F_2tyiBh7FvTExMjgGLuKEnfdb=w531-h944-s-no-gm?authuser=0', es_principal: false },
        { id: 'img-vc3', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczPm5AORC8CpZAEzkE18pjIs7s_LKm4fMVVG90L7USKC557qKqDiSxoZU5TuWXEN7_ZqnLRBi1x1NRQ81Gib4UdR0vW5kSazWd_YKg5MGJM6gJI3cyHQeU3ECHx6T8mBAxOx7o9BS9iq-TP5M2H3jWKr=w531-h944-s-no-gm?authuser=0', es_principal: false },
        { id: 'img-vc1', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczOLyjw5PG1RzxEbE1aqZfrPIj71xItevgxczk6xoxSjAkMZk5_7DYSIVKAmtm8pzMvCdkN4P2uhbY4Bb1eXRi2KgJ8NScENV7hz1oCTbrnuOqDEQAfSFS-0WjPO37R0UOz3onxgliS_-zC50yHuMp2R=w958-h539-s-no-gm?authuser=0', es_principal: true },
        { id: 'img-vc2', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczPXpx_k5BdTaPY-Elyt7KirJcRmuRTSUabPq8IOg0xQF7KF1JfUEUip6Fzt3BjXZIklF95LNESPVnlzAfQwIj3i568GJRCy5OxQypAQJ8LOLs5hvtX6-5Yr6MZ72Onvi0bLFZM7yyO90_z69BJgHDY5=w958-h482-s-no-gm?authuser=0', es_principal: false },
        { id: 'img-vc3', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczNifLB9_ciKMTsD0ck8866JQAb-Jk_OepJtHrbTJlOW58VlS5HFIkvPq-jO6v8iERcqqw9cbRXBwBTH0u6Pzan42sVq7AGEW5d2OUa6KrpulwKmGOLedylwFAaa_SuH5sYkfpQviPRh9ene69wFabfo=w958-h539-s-no-gm?authuser=0', es_principal: false },
        { id: 'img-vc1', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczOGuVJMrH40kjlDZdBnprpKbUkiCSWFCS9Zl_slOozrKuNbisX0tdI6ORTN-N3Iidb2pmMYTyK7I3jbPlCiqt_ZrLUnxiooFMxB5XpA_ejx7xCUCJluIKyVAuVZvlbwD62Ka2TfbaNqPkNy2okx5QoN=w958-h539-s-no-gm?authuser=0', es_principal: true },
        { id: 'img-vc2', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczPj8UEDTAuEDJ-vqrLRtaNX2DpzsqGlsEFwai-D0UX-u_niMysjYUX_t9Lx0PS6oSewLlolcFtMShoTh481803reVLNctunyJcNq2ykcZpYNU-l3JtdFk894X_c5KHzbjkJgV7zJhiCBfm2iq-SVL8e=w958-h539-s-no-gm?authuser=0', es_principal: false },
        { id: 'img-vc3', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczN9SZe28Gb5LcpKyfD6kjpphTmPDapy2xs0mCIMs9JEuDwVdH4I7nqzu5ACfE70e1UzaC0qmeiX5KNeKotqCVV2TRwwkczt7EIyrfKVuMg3dWk0UvRlyVfOuTdygU2pjIEAc-FU2mAId0oGC8Kux14S=w531-h944-s-no-gm?authuser=0', es_principal: false },
      ],
      es_destacado: false,
      estado_publicacion: 'publicado',
      fecha_publicacion: new Date().toISOString(),
    },
    {
      id: 'venta-2apt-rambla',
      titulo: 'Propiedad con Dos Apartamentos en La Rambla',
      descripcion: "Oportunidad de inversión: Se venden dos apartamentos que conforman un área total de 262 m² en el sector de La Rambla.",
      departamento: 'Caldas',
      ciudad: 'Manizales',
      barrio_sector: 'La Rambla',
      estrato: 5,
      tipo_operacion: 'venta',
      tipo_propiedad: 'apartamento',
      precio: 900000000,
      valor_administracion: undefined,
      es_negociable: false,
      area_construida: 262,
      habitaciones: 6, // Estimado
      banos_completos: 4, // Estimado
      parqueaderos: 2, // Estimado
      estado_inmueble: 'used',
      estado_amoblado: 'sin_amoblar',
      tiene_balcon: false,
      tiene_gimnasio: false,
      tiene_piscina_comun: false,
      tiene_ascensor: false,
      tiene_porteria_24h: false,
      tiene_zonas_verdes: false,
      tiene_cancha_futbol: false,
      tiene_kiosko_asados: false,
      tiene_salon_social: false,
      tiene_juegos_infantiles: false,
      tiene_sendero_peatonal: false,
      imagenes: [
        { id: 'img-vc1', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczNIo2ZE7B9sHsicL4Zf7IEZGtrvxrfH8dkTaQkc37l6EtvEWLsaP8CdIE5uQV5xCBDK1mSSPfKG4y7e3KZBBsfkE0vvuQGafHo56ZrLjQylvBB3b7CKRFy94M98KelfE-DSXcFNZ0JysdN3uQdqXIKy=w958-h719-s-no-gm?authuser=0', es_principal: true },
        { id: 'img-vc2', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczM44ieUWTOgcD1STu6yydqid8xwoDz9Gbyh22ARQGuQgG-jKigq7FjBPDIDP_rdufDw6CdiGf0FxB3LuaBvnLdBGcspIWanWMTK4iexdbFrz2dS4p75MIMxj7tOniYLHbM84f6xL-6F-VeHs0KoTop1=w958-h719-s-no-gm?authuser=0', es_principal: false },
        { id: 'img-vc3', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczNzgbWOAYYyZEH_sa8njeVf-cNKTPj2CdU49uXmVop5ACyUw5BDN4BcAiy3OyQ2TH7BLPOaQEv6-MfCtjDVqmZcaruG778lfPBWpOYyiQRUD0iUWTFhz0F9vU8RMPAhjYpViZqPmQTgN04A9A4iDd73=w958-h719-s-no-gm?authuser=0', es_principal: false },
        { id: 'img-vc1', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczO83UWHmpqUTnmuIQpunwp91nKDTpradgDMPxR09oMnTbrdKD88fI3X12ak0-h9pFR--mh50rsLgi9jrdEKs4gtNhOOCTYdTdwuh99MfkyyU0POMqmVKUHQN-cyIJ70--8CyLhce-SMqkOeokdSgBLU=w958-h719-s-no-gm?authuser=0', es_principal: true },
        { id: 'img-vc2', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczMK1--GNfQJg-Rgq7MEkCluPUj_iyYUlV9aCKIVVti9NN3Q0M8WLTqGA7FZktutmLDIMgO6Ih2eORP7XBNZmwOXN9yNfx3PDEALKY9hhHuIiIb2IPZSsFRcdhy-iO8_U0uCmm0AkfPw0LjmCz70FFsC=w958-h719-s-no-gm?authuser=0', es_principal: false },
        { id: 'img-vc3', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczMuzKLWUTDcPWRtoV2fMDT9T6hnyOXPxumEQnrbwiqFpveYG0Wq88SZRNHCskykUVq6pXIgjP44jGA9NG17jKNbSVtRu8hXzJTvBj4YlEqOye4QZ-t6Cx4eaICJ31q2LZXuhMve8TN1EgftzqLPUVdB=w708-h944-s-no-gm?authuser=0', es_principal: false },
        { id: 'img-vc1', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczObYw-otnCNSv4Eprb8ar8Y1iDN6vURQl-DLdMD7hFhvrpkqM-xjLd8-Hxpd5_CoxujvXkAFEMCKNLygWL7sRzSF2ZPOt70yFj6fYIMxk5LZetiN5O_cLDoiwGKytMPwvktMvvPdp6jUOFFUF0h0Siw=w958-h719-s-no-gm?authuser=0', es_principal: true },
        { id: 'img-vc2', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczOeVuVpCuvC11DwCssYCkKHMPi8-fPcuI-7pEwFjh3HCyonCvxP7AD3-LTcsta2HTuspb2OkTdMVnyeuCFWcomT4J6RSnmACXFVO2plUK4Rhd0bqXUsZracXzmf487lDMRJ5IIbdhELJPtHhKAxIQoU=w708-h944-s-no-gm?authuser=0', es_principal: false },
        { id: 'img-vc3', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczO1vf7rbw9VWSZLI_jiRTWF8zgaayf2rWOI-XIYmhY7hqMfg4_BtRVX5OTHCp4tmtA4vPnU1U9GBCojX0sHQTaE_KGkK7B4fGGni68JeiHdNvAVWhKpmR_x7OAjEi2N4tMLkUo-ZlgPghIOMh6u32pn=w958-h719-s-no-gm?authuser=0', es_principal: false },
        { id: 'img-vc3', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczNcu-BX5HU1E_X3n6Um3kjnPN-vTqoth8Z-wqS1aONqIA1FMI0AOl0QlV0AQKDJ7blgCwqTZcKQ15M0DCMvFMB7mqtGPJxoZTjnc14ZVbYhfw-6AqPxPriQjiIqa1Sti325QQjo0FX5mfrGRMKJEaj_=w958-h719-s-no-gm?authuser=0', es_principal: false },
      ],
      es_destacado: false,
      estado_publicacion: 'publicado',
      fecha_publicacion: new Date().toISOString(),
    },
    {
      id: 'venta-apt-lusitania',
      titulo: 'Apartamento Esquinero en Venta en Lusitania',
      descripcion: "Luminoso apartamento esquinero en el barrio Lusitania. Dispone de 3 habitaciones, 2 baños (uno en la principal), sala comedor, cocina integral, zona de ropas y parqueadero cubierto.",
      departamento: 'Caldas',
      ciudad: 'Manizales',
      barrio_sector: 'Lusitania',
      estrato: 4,
      tipo_operacion: 'venta',
      tipo_propiedad: 'apartamento',
      precio: 220000000,
      valor_administracion: undefined,
      es_negociable: true,
      area_construida: 62,
      habitaciones: 3,
      banos_completos: 2,
      parqueaderos: 1,
      estado_inmueble: 'used',
      estado_amoblado: 'sin_amoblar',
      tiene_balcon: false,
      tiene_gimnasio: false,
      tiene_piscina_comun: false,
      tiene_ascensor: false,
      tiene_porteria_24h: false,
      tiene_zonas_verdes: false,
      tiene_cancha_futbol: false,
      tiene_kiosko_asados: false,
      tiene_salon_social: false,
      tiene_juegos_infantiles: false,
      tiene_sendero_peatonal: false,
      imagenes: [
        { id: 'img-vc2', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczPKzOTHUIQd2HKMJO-h7uwgsr2sZm2eSq59tHtB3uOoOqi7exZ6lFugo1qlSl8CY1bM0qFAFG1TaRuVtV-qogSOOzhNE_XtxRwu0IAth6R9iUr60Ohu9HCzVA7_MA49u48BSDeAbewLdyQI3_fX9i-6=w720-h513-s-no-gm?authuser=0', es_principal: false },
        { id: 'img-vc3', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczP8FlHLZvwUroDspDSmWl-Ou1vfedwnETgGyaPD9WPBw5-WCDmEYOqTE31pQCxr9y-YzNTUgBD7KkkmeSkR7aLTOx3rwPudK57y915LbCGYUyJujR5MdGMtOD4R3flNdtMIp6QewttSFUAH2oU6DB1z=w720-h520-s-no-gm?authuser=0', es_principal: false },
        { id: 'img-vc1', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczOhogKOcNJLyEaAxLRuAgH0YKISc3i82cjqelEfImURhXWbosBX1snq_MENyBrgoCFRInMo5fJF0moPic0ZPOyIffpbJZ6Ayim44K9Ve6EjhPYDCaN0t8f0NaLZNOrgWOX0qnVjQK-K1_4AC1JNVzIg=w720-h514-s-no-gm?authuser=0', es_principal: true },
        { id: 'img-vc2', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczM-docHkrGG9A7f6o_SpaZzBwBBoIrL51PpZ-Mhe4-OaKUfNF10UHOft_LS00UQBb24BXP41f6sAwiiJTkMJXbDRrtP7CoJ6eLjQv_71Nt-czZ2ldLo7oJiwwegGaE6wP9RK1u4MaPaTQxarGRWtjMj=w720-h495-s-no-gm?authuser=0', es_principal: false },
        { id: 'img-vc3', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczN_5pm27_8wv_WlW1qMzblY9HOzcV5QJ_l9v1pRBtn-1bo5wC4cIoE5l2TvTsRQ0ZTEXP7Uf4ulDol9TLZZ6p4rCCG45khwnUJJe3lOkZnn1tbCZg0pxgWzaOqr8MAyBp9M3m49cDpClT9wIlOorz0D=w720-h510-s-no-gm?authuser=0', es_principal: false },
        { id: 'img-vc2', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczPIkgCmdPSDm1Gg_gFQLQTqOyeT9GPtqbjxwjMI1KhsavKTBYguFeFtStjNJ0AcGdjPL4lHjAuiP6tCtadaOnxf_zR9wKianD2rtihVSYkPpZ3dhtYRCsrp8IT5MbOWrVSkzUHFldvnPWRT6xoWCVuz=w720-h526-s-no-gm?authuser=0', es_principal: false },
        { id: 'img-vc3', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczOianI8jdNhY47Xt4I323Mb_xa7ypLvJsMLyVJyhB5a7cnpulNeloeqgmXZgNIKft0H46V4_gqGGlCwi1FhE-zJi7wKw_C-3VZrC_ZXWJn0kZjPMt33Q5otsJ-2_moPC0wCfCORrXG3akIDfUBQXNDx=w720-h505-s-no-gm?authuser=0', es_principal: false },
        { id: 'img-vc1', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczOb1eDGuIJ9YnRA5OUOuqfkEpYsD_GT_gOwpvPmx6zPBpUsqX1Zkwy1xJfDiiPP_HRgfrX23G0pabb2jg_CN0e1WC1tU0MY-8xOKZ_SbMFKxR1xZJFrSaRCJhxq4iC9cImIPPzhnAdUSQ8Jq9EHA-13=w720-h537-s-no-gm?authuser=0', es_principal: true },
        { id: 'img-vc2', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczMdiqO2R0dyP3rRGTzD8l4MD-jliza9S5wmzh1RgBm_R6JcWFyp3AmZAMbdTbXRIlk7wW1dwJd2fCVIQa3htECNsstSYb6UrSBvX-JB2uckws9ut7tDLbg2a2ohLUkkObgzIgCj_qOaTnwMgqvgCCnj=w720-h528-s-no-gm?authuser=0', es_principal: false },
        { id: 'img-vc3', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczO1lyfGNYn2sBTd5NZU6HZWBOb_bjkdkDQDjCc8EhZb6O-Sf_3_MQEklDJQcxkf_T8e-d98X_FWDUhAZiioAbAkmnwY5whbgR-5J1vAX-2WLELjPIB48yhdFartxqX-bPfEwlB3Ar_3PwC7pT2B0mul=w720-h524-s-no-gm?authuser=0', es_principal: false },
        { id: 'img-vc2', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczOIVeZgR8pGBXBfRCuTrf-Te9ylkJe1kxdshN8IB-9ystjiM2bdkxwmsTyr7k0RlgCiEX7akWsYMs_D6PN5jfC6PqSiXeebD2bwypZfC3a2GwO_6RLaOdztkNxVt0SHVVnLqwo8gPXJvTtZdln1MaAW=w720-h523-s-no-gm?authuser=0', es_principal: false },
        { id: 'img-vc3', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczMy76KIYWeVym7Gfql83JrVoofDuQnX_jQ5NVZCyDtn0tbYgz1EqTw72C2jtXFRkj5kc1zPLfeQMGq5uu3sbPwntY7y-bl_E0h76mkS9yA10meZtD_Zswc0TdoE8V9Vo63_UkqznkCb5LRFnev6Pd0b=w720-h515-s-no-gm?authuser=0', es_principal: false },
        { id: 'img-vc1', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczM0gvctSwoPTyN7J7v2e463u6vaV53lMzfMKOa0koeY0rZ3MjMfopfRtRrGjyrptiAJOVvX-1LaKPEcuAYfIBVvoMOp444dw0BPkN2SLhpv78AnI7JUMzBtQdrshB0QCcBUCBgMOr4TLkIQ41LUWAlh=w720-h505-s-no-gm?authuser=0', es_principal: true },
        { id: 'img-vc2', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczMTsHCbxKQ34jQ7H5EJlkYgyP0JiycMcLpgQLE8WMB_F5ROykFIO9enjBNjlXfJSF2acnzNecfUz8NT21yN7HFM8IONV_nqEIgnH89jGSE6zfpf9IZ9rWIwJ61Sm_LwhcKZqN3DZ76h_T06FNOkcD3l=w720-h513-s-no-gm?authuser=0', es_principal: false },
        { id: 'img-vc3', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczMXBi2Sjmd_DaUq0Egap2Zp8KwTE1z1xelARNArTIkNiSPNblKx2Tv8-8EJWxn0nlm1qHfZTxRcqTW5DKGK9eL_nO1tk7rSj-uuIBco44Gb3b2KwgwyuRxIbEO7ci0YElqNH2e1AAHBw0aPGH5nCt8w=w720-h495-s-no-gm?authuser=0', es_principal: false },
      ],
      es_destacado: false,
      estado_publicacion: 'publicado',
      fecha_publicacion: new Date().toISOString(),
    },
    {
      id: 'venta-apt-lujo-1',
      titulo: 'APTO MIRADOR DEL TRÉBOL',
      descripcion: "Espectacular apartamento de 116.91 m² con terraza. Cuenta con 3 cuartos, 2 baños completos y 1 baño social, patio de ropas, sala comedor y cocina. Incluye 2 parqueaderos. El edificio tiene 2 ascensores, gimnasio, salón social, área de juegos y vigilancia 24 horas.",
      departamento: 'Caldas',
      ciudad: 'Manizales',
      barrio_sector: 'Sector Exclusivo',
      estrato: 6,
      tipo_operacion: 'venta',
      tipo_propiedad: 'apartamento',
      precio: 950000000,
      valor_administracion: undefined,
      es_negociable: false,
      area_construida: 116.91,
      habitaciones: 3,
      banos_completos: 2,
      parqueaderos: 2,
      estado_inmueble: 'used',
      estado_amoblado: 'sin_amoblar',
      tiene_balcon: true, // Por la terraza
      tiene_gimnasio: true,
      tiene_piscina_comun: false,
      tiene_ascensor: true,
      tiene_porteria_24h: true,
      tiene_zonas_verdes: true,
      tiene_cancha_futbol: false,
      tiene_kiosko_asados: false,
      tiene_salon_social: true,
      tiene_juegos_infantiles: true,
      tiene_sendero_peatonal: false,
      imagenes: [
        { id: 'img-vc2', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczOGyPjJS6ZU0CBuXKaAIDyMvZZY35cRSz3dP2ekNpJQ0BI1e2o3rUAmZxQfDQ9wj-XDn05adiqSRYueFwkq57L3n2kKM6982J6CUnLI3xgLHRuB04XdM0mJNRog5D674G2wZlcuda1Ys2o_jb2Q1CBu=w958-h719-s-no-gm?authuser=0', es_principal: false },
        { id: 'img-vc3', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczNoPy-u4I99PpypG406pIEGb3HUc3x5-V-nynKUg2-MdkF5WRzp7xcfIqq4DNz0PPa0rNHuK__woSP4GnDaRfQuKob9bJqnwiabSImA0bBA7Lh4a8cK-lhi344j-vep9uVnjMHRMq46Ssh5koJ1XiiL=w958-h719-s-no-gm?authuser=0', es_principal: false },
        { id: 'img-vc1', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczNShAvBGm6hSFZAYe_iUMbbTExs2g1iijaiUZzO_lT4tCJMjkDN-mqWVN-iN0Py7GkeYAHxjp_GpDjzfBwhspUnRwTOGzYGZu5VQlSN4gs6bwDX3JEG9b7Ffx4UEwFXpw5rYhxr0A_nFHXVFRXlB62G=w708-h944-s-no-gm?authuser=0', es_principal: true },
        { id: 'img-vc2', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczOGcKGSqyt8lx3pDSIh0Se4yyCyX-UggGEwkEmEN_Fz-2WVHdhWI9Iv6t7zCJcH-SceN_h9CoJ0V9ND2cbm9QC73DyKfrWjXklH4FztHZ0cbbV7Sw6-pIU34yl4fiIBw6jJxnn0yZ-EPMYLeDlmBLua=w708-h944-s-no-gm?authuser=0', es_principal: false },
        { id: 'img-vc3', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczPqy2hw70WbW6j35mGRcID7uOB7vJeLQuVg51AWdAcG_PwkKMvYbQ-z6gRaPL42xXVRvXhkmBkvMYspjpC1EAUOfRZYD8d3kvSslt5JmA6UjAM9lraMIZqGtYvd7oRkDpCrkYBoWp5MGeSy_15VqbRl=w708-h944-s-no-gm?authuser=0', es_principal: false },
        { id: 'img-vc2', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczO9-aMpgbVaon9e7WgT9PpJ-EjDsr7B78F53bhxPDzL1s-XJkQXmj4NCphOqVRKeXhgUV-ImZW3i_Abj7jPR8t4b2pKF2ZCmZ2uy5Zfae673ah_OpjbOc8p7Z6GdGiwSx4P6FDZGIRXMCBz0RRarCCm=w958-h719-s-no-gm?authuser=0', es_principal: false },
        { id: 'img-vc3', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczM-iDJQqrTRHONXBO4x-sMPNr2vbbU0r9XURl6-qpfBeSGnT5buf1Ol7Am4ggDSAJZHA0TappecGLAd_Gp0xOZkMiOS7QDJS_OE1Ri2UVWKbMjxtCDFRqriZy-_ta48Cuin2FIxILo76jT5xhf-1M-7=w958-h719-s-no-gm?authuser=0', es_principal: false },
        { id: 'img-vc1', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczOz5aoHhaW_xUCBQARXr0YUuPruuE1SaaX5p2656_YonWoLJP3PkzVON_V97m9vnn2JNvR7sH1SBmPpsv3u8-PntL2qqY6-Jv9PBWwOw_Xz1ao5EySGdNakwmQ2lQwgQ6ZwIRbVOz5Qo2nEyEz-RbIM=w958-h719-s-no-gm?authuser=0', es_principal: true },
        { id: 'img-vc2', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczPhjhy310qucnz5C1l2fyzliSG-nDoPDvy--GvL9Q3PQRWNpd5TjLDwbjEtDmrxcBkqx2pjR2scGqsphfVt8Q6ACqRwLo15YyTV9NJZ2C_hpsR6SwRM17xcQCbFfFz5UzuulvZLqR9dD0OJA_lIS_r4=w708-h944-s-no-gm?authuser=0', es_principal: false },
        { id: 'img-vc3', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczNlTSFIUWhZRtL4DIzEhUafBin1FfhWVIeagzxWGZxXAKaZIjeIyhydou8p_0hurXM5BT18Hwmvq97faldldqNfKVKSYp7E7gcMT-iyGaZb4WSp4QXp3hlxu2vZml0VMKhX4aqbcQcNj2PJhw9528z3=w958-h719-s-no-gm?authuser=0', es_principal: false },
        { id: 'img-vc1', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczPL5uoAJw35XODrTV9vrxp_0BqfF84aaXltNIz0DmShMzoF1dEmsVzITKMLGykIOtzDejZaggYTtLP3M4xGaz-zm_TqBKUEzOEYJd3LmMrBI_p5FY-px11CTiQDCekY9HDtRx2zoAsXquId85xmK3nQ=w958-h719-s-no-gm?authuser=0 ', es_principal: true },
        { id: 'img-vc2', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczNjO7yZzLBxEvAz9tKAtDGGt3mnGO6D5QxYD1BUMep2pb-QubqIqxZmyInELFlHKb9XCb2cWu_0TE5SzJkBl9Fu9gAI3Fc-IRbJHmQMIrxra9BFoPikqF6jawBGNumom43blCkX76WSvheh4narl-ij=w958-h719-s-no-gm?authuser=0', es_principal: false },
        { id: 'img-vc3', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczN_8qczExHgEkteFmhXVXMcETENjL_K1rD0212XOALTlYPerakewr0MBuKBks0r8Oh0F6MWB8_NQrC_lONqQ3fBXKE-_cZA9xg4K4RraQ7xJk7HVeWetgDlnc9dmb_cCE8vnYnp2gJIKq8sxTwrwN-n=w958-h719-s-no-gm?authuser=0', es_principal: false },
        { id: 'img-vc1', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczPqEnTwLa1ke-bef1t7CalmpujoKlQRpuCoVb5SUtZMR27U7O_bBiK2ZXWCHHE03QYadCSz07lhCrIQR0RWv1bPtT0z_bPYdHE-v18zzAIyKs0Rvaoek0BEJYss7yfQrO1-F2UTM-NH71FKLhmD7Q68=w958-h719-s-no-gm?authuser=0', es_principal: true },
        { id: 'img-vc2', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczPdCGYo-k0EnGVF-NcyXfOa65M_6QpOm7bUCFW8pa2RfD6gSWDRNzyRL1msg12FGRz6hISFNBl-nYhpaE0pPqVs5E7BxhG5l2rb-qIg3GlnlAh4oOUOtftsAKYOAfY_ozgCrTPQMaXm1QNNQQ41RmBh=w958-h719-s-no-gm?authuser=0', es_principal: false },
        { id: 'img-vc3', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczP0vjR_s5gKMeOg32lEKIYRhGJuB0hf5-duPS8wjZriM6e3XZDsn8IHvA_Ez6gPVPT4Qylnl98tzKAO4pxwUFfuJ11mdY_C09k6Kfcz8qEUXUU8IY1XcJFr8hAuTt22KGXN8Ry1Czer47d61eVYFiRO=w958-h719-s-no-gm?authuser=0', es_principal: false },
        { id: 'img-vc1', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczPkR1iTJFWFZdAQkT3tBLRsWHWq53gNubQbsuKgAsmE7PlMbZbYs8CkqzLppvSOI7RogP71r6YE8SB7INAKR5mP0dluMhShu0013eNWtGSiM9y5R2HPGK1Z_VfZNC9NuaJC55KVQ62sJlWTarKMOV5K=w708-h944-s-no-gm?authuser=0', es_principal: true },
        { id: 'img-vc2', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczPXjruPRIh79tYZzjnwnJPaIYQ394Td3d2NusAMoPDBC4OTA7pSScToXziU-rJpr48MHG7FhbJ49rIdp1LhEQ6LfKbaiFS851aR04hkbm26xjOZXw21iAmWBi8TFD3ZWxrn5Hmdl4_CW1TPUPb226Ev=w708-h944-s-no-gm?authuser=0', es_principal: false },
        { id: 'img-vc3', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczNOnCH2mI9LNjY2IrjDRIOHgDrXyKtk3M6Skybdbs8Tj7V3JX-p2SI2yx-N9RTJOX8PAX44-9-ZazcmgrGu5rTVnNstnaApMr9tsNQUIW-u4aL-YrOJ0IpkzfN0ybiIM2uKGjwLLGrM2IXvi8Uk1Ms-=w708-h944-s-no-gm?authuser=0', es_principal: false },
        { id: 'img-vc3', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczMfUgN9_mOyg6OrKX-yv80gECfLJ12-kw2H_muLUwAtd1CvGcUmM4QCuvFOKEJBeFy_8vMR5EoRdd-NAAOQJeeEM3LGtbYPuP07MyFG9bJNCDsTAujDrXw1YB23ADmaRxr70vcSSIUUhO88sxudmd-a=w708-h944-s-no-gm?authuser=0', es_principal: false },
        { id: 'img-vc3', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczMVyR6tO_XflXXAb1IQ87ERu87uwcNzZCzx6C2F4BuvqMKEU_hh6_uOHNfPH34b2difaUUwACIQqp1OhdRkFLhmkfxolmETPYflJ802pK_MDp0dvVR_2VOjPwjEdEtutWsLJOqvd22Vb8i7LfRNZCJE=w958-h719-s-no-gm?authuser=0', es_principal: false },
        { id: 'img-vc1', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczOBikDc58oAPDPodwIfE_ZX6qP4VVs2oZ1tSbXD5DZ80pwpdh5ZrLvLmFIgNq9_GTI5vs8sHpo_9-dseGZqEq4VB3x0kyP35SbwuTka2Kwj0fGBgkxEC7VmTQL8QS_x9-XVHwWCZPOC-fhPP8rHcsJ=w708-h944-s-no-gm?authuser=0', es_principal: true },
        { id: 'img-vc2', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczM_UoYebu-ZHAii5UJ4pgF9FDeCAnyYqf8xW8ZH4Id5Ou3hQh5mI2zU7FazCMWXjRTO7W7LUb-oMaCvtFISZQq382Wg012tAw-JImsNpAdCc0y2o3mje67XedQG0aRD-4PrPxyzonXRTpBNoCvuHH1A=w958-h719-s-no-gm?authuser=0', es_principal: false },
        { id: 'img-vc3', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczOiAaiEgoAMWvG1N677jwNMxicikcSIBvI_jkVjs6rQZqiJeXRPfrrfCdK9wzoHRMDmnN5Js_zeBRFz6Zncl_W5g83aqO_w-tPGkDFIS3IrZepGmQZDo3ezPY_3JMLd8bzfYrFuRPu5hYZDqjW1u3_8=w708-h944-s-no-gm?authuser=0', es_principal: false },
      ],
      es_destacado: true,
      estado_publicacion: 'publicado',
      fecha_publicacion: new Date().toISOString(),
    },
    {
      id: 'venta-apt-trebol',
      titulo: 'Venta de Apartamento en Altos de Ciprés',
      descripcion: "Ubicado en Altos de Ciprés, cerca de la Universidad de Manizales. Cuenta con 2 habitaciones, 2 baños y parqueadero propio y para visitantes.",
      departamento: 'Caldas',
      ciudad: 'Manizales',
      barrio_sector: 'Altos de Ciprés',
      estrato: 5,
      tipo_operacion: 'venta',
      tipo_propiedad: 'apartamento',
      precio: 300000000,
      valor_administracion: 302000,
      es_negociable: false,
      area_construida: 67.54,
      habitaciones: 2,
      banos_completos: 2,
      parqueaderos: 1,
      estado_inmueble: 'used',
      estado_amoblado: 'sin_amoblar',
      tiene_balcon: false,
      tiene_gimnasio: false,
      tiene_piscina_comun: false,
      tiene_ascensor: true,
      tiene_porteria_24h: true,
      tiene_zonas_verdes: false,
      tiene_cancha_futbol: false,
      tiene_kiosko_asados: false,
      tiene_salon_social: false,
      tiene_juegos_infantiles: false,
      tiene_sendero_peatonal: false,
      imagenes: [
        { id: 'img-vc1', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczOrAutZJL9riMj9jNH9Fwj4WakbAHREmBVhDb_xgZdLs-q4E-RfK2w-ICnm5AGFcCS-LVWyxEXoYr3Nv4f_E7vdoWsKl452xH5A5AxI69gD_agcUrZN7oDOKgYyUhzcGhVzjkPc8njXbDHimUH_MczT=w1066-h800-s-no-gm?authuser=0', es_principal: true },
        { id: 'img-vc2', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczPz7GymidWOWxq5cbnLWbyK4NXW8sXjoTxM98Lgm_IxwRwSDn4v_TvDMcc4EDjrzpJMIjVqKEIkxAwAIvOtmiyIjFzM2rf3hnANW4nn0kfEUHUr4n9LW9iTn7tVSVV78mAkbFlULxoOoAeEkynttuA6=w708-h944-s-no-gm?authuser=0', es_principal: false },
        { id: 'img-vc3', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczNVA-5RAUySpkJ3pfbATobyg1wQrENCkSkckz_LiW5pHRNiOLmB9R9WMQ7XQ3zTWRUWApJG2XIjUCe_VU5Nx3ya9edEizYzoDNW0hCq6vvhumcYXgVjXZkhFhduyRK0aNnGmx0FE3VQsEI1lahNPHU9=w708-h944-s-no-gm?authuser=0', es_principal: false },
        { id: 'img-vc1', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczN6g4aebxqdNwJvxBPSwK0UzYYoD_ecH6mHJ1hgQe2DrIYJOpe8-doXx4qgjgyjFca557e5OgHHK2pKVoo7OF59L291GaHENyUOVwfW5dzr0_x9ufW8ObkWwnG6kdYxGQkQUqEEFM6T4gTcyB83enIz=w1066-h800-s-no-gm?authuser=0', es_principal: true },
        { id: 'img-vc2', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczOXc7VNGGn6B604Jl-V9lcJjQ5ZfSEVfUcEbO55bmFpMJbTJZee98toUOgnEjVeHhN6Oj3GyBzQn_jXyAo32zcZhODRVjDY44F3a-6J76SgtVA2cpV17virxuEIfkZ3pkYTSEzQY3bYaSx_iUvnSI06=w1066-h800-s-no-gm?authuser=0', es_principal: false },
        { id: 'img-vc3', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczMCewLbTQW79Lbwy0ibzbWOL7VtK5cseTZj05z8EDaoxsXspLD10ZZOWfvEUW37r0nORSPAMfdRaEO6LbT1ZlVEZZwIBrW2WTC-GvPsBd8vgLT8rxLfgGdgDRZ7Q5kqiNl1XKA00mHpMQSB0gcDGOqi=w708-h944-s-no-gm?authuser=0', es_principal: false },
        { id: 'img-vc1', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczOcvmYdfvlrRdVRyScvTC2VT0MA8mXGheEepHgl7FSqEAuFt4tFLwWfXLYlR0vDmmz5FsmgYCjbfahuu0qP1U05NVHQq_0kJadFTUzvBscWBDdIHfO0lohiHH9aFnHXuvLI-0y-aRXs9oKtSe8nK6h8=w708-h944-s-no-gm?authuser=0', es_principal: true },
        { id: 'img-vc2', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczPXyfWXNP1v28kizdLiVGdx5SRw8pJt9jvQ-oQCx8Q-XTAQX13_IXfcuVx_2C0p078_S5mM_R-mklyXl6YQO8vWnFME5mvGSGSV8V_-M1fNWg4EHmKEwMc6NW4WT0lyNvL7TFSksuJn-RN3TbxgDB3b=w708-h944-s-no-gm?authuser=0', es_principal: false },
        { id: 'img-vc3', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczM6TTWEmWawfEZx311ik6hvJld6ZaDj5DEAa5gXzAKNf6HPaIIwhnBvhbP0HLpBEEJyhJSk63j7uSd997Fp9c78O0ma_3GFNV9wpjQCvCEgnNY55fkaINshZ1-jTvcdp9XHCxGCAANLwM0OLfCNu75-=w1066-h800-s-no-gm?authuser=0', es_principal: false },
        { id: 'img-vc1', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczNBADmKfHyHl2uGYFjuCpbTNoHGrtf16DGdFgBi4qhn5ZC-h5kTCVK-JgcmBDbrS_-BzGj5azdMkCUJ2jC_YlQtJJKJ_CSOWQiVBW3jvOkqs3m4H06Y6eXjKpKinKuWHtfEsOgi4iP7EBmmv9nGQu9y=w1066-h800-s-no-gm?authuser=0', es_principal: true },
        { id: 'img-vc2', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczMX9vaABZLSi_XCNPTFzCl6CCmoSshjA6f4apYseG9Oo54PjKrtjJ2u9kWteorg2cO6quh7eR1UM3Jj82cuOZAyxjU4pdG-2SM2FlFi8M5N38pJwQYrhtcCdJr9PQF1b2ziGGvMIlgFvjqtrhKDcVa0=w708-h944-s-no-gm?authuser=0', es_principal: false },
        { id: 'img-vc3', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczMi0J7GYaKfHlYeUR1eJuJkWDf1lqvweZNm_7zYEgIrixkbQM3bsH9uWOnRI3o-E52hkqMpV2MfZC4FhyFONxmUULdfwpKt5swlXA4bA-cboXFMVl4a63gAo74lqoS-aWLOuac2Z1YutvMJEuWgkGUJ=w1066-h800-s-no-gm?authuser=0', es_principal: false },
        { id: 'img-vc1', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczN78HP-fw8k9B1nXoNikifC93b4UbsMsNJaYyFgyrT3xI7NaX9OiEowLIVdLOoh37UrmOIBLqyOKNm4T3mQtTTOlPCNpwgOceXljfFnlFiObhV9YWd0uMYUqsXNzhu1zppR5P5iQahmC6XkWWWj75Ne=w708-h944-s-no-gm?authuser=0', es_principal: true },
        { id: 'img-vc2', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczNVycaqtjIz9cutd9vtXLARGyOQbLodIQ5DpTep5OR5YNWdnveZ79UbgVY6cJcwWq3obRNd7V56z75F6k0dlhyXzQqYhx4KE2LaCUs9yVDm5eDqpnv_QECoYzbldd-ZE2LuQKK1AIseqP0Msu1AFFco=w1066-h800-s-no-gm?authuser=0', es_principal: false },
        { id: 'img-vc3', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczOLv1PmwcqCSlDci2538SeulWgxZxAne8xWRnAOWKlkrOGy0WxHo6_oXQ-cfTtQCyI9yegrkHppJfoMi4e4qhtR-hb242NJQxmowEu9ulLWe360OIoRXrd4EJB1R_ETys1S4uiCwrnsRa3vhnUv7i2c=w708-h944-s-no-gm?authuser=0', es_principal: false },
        { id: 'img-vc1', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczN6hqP8sE9sq1UnrsTu6DdqMDG5BeRk7hTg4a7xXNpwV6TqGWAiQCzfARtUv9wmhKAmDk4wkXEqYjnrfwirJYYc8Ar3gF0Lsru2OpnQ9ECJeQGEwFohw-y46he56hU5d-Pl_TJEAlakcmyHQOCDZRZX=w708-h944-s-no-gm?authuser=0', es_principal: true },
        { id: 'img-vc2', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczPy7PaxdliyUh6KtTH_4H3WOMjxW33_I5vkkPilfSILQ5Ar2kfYgkkDOp26dfWiAWjD_cjbLSGpgYGwv2IO5uUYiHTnjO6Pb4ke09WNajlhjE8n9XmQ8cNpNlQjxvQ6azaXxXvLYcRB0VTxTnkA8snA=w1066-h800-s-no-gm?authuser=0', es_principal: false },
        { id: 'img-vc3', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczPfkVJfE5pxBaJmG5MzYklSaqO_Hn5I8hlzPAeW8Lo1NtEqQbKyaYBXpnZALPeurcV7rXKavkrdjZ6IyHeDvb_KeBjqp9u5PyfVSyASn3g50uy5tqNj57UFzXJf9p5GIDq9_IuP5DAK60oAr3_6_Y-e=w708-h944-s-no-gm?authuser=0', es_principal: false },
      ],
      es_destacado: false,
      estado_publicacion: 'publicado',
      fecha_publicacion: new Date().toISOString(),
    },
    // Propiedades en Arriendo
    {
      id: 'arriendo-oficina-cable-exclusiva',
      titulo: 'OFICINA EXCLUSIVA 43 M2 EN EL CABLE | AMOBLADA SIN COSTO EXTRA | ¡ADMINISTRACIÓN INCLUIDA!',
      descripcion: 'Excelente oportunidad de arrendamiento de una oficina en una de las zonas más prestigiosas de la ciudad: El Cable.\n\nEsta oficina de 43 M2 está lista para ser ocupada y cuenta con una ventaja única: tiene la posibilidad de ser entregada completamente amoblada sin ningún costo adicional en el canon de arrendamiento.\n\nCaracterísticas Destacadas:\n- Ubicación Premium: Sector El Cable, estrato 5.\n- Canon con Todo Incluido: El valor del arrendamiento ya incluye la cuota de administración, simplificando tus pagos.\n- Comodidad: Dispone de parqueadero y los baños son comunes al piso, manteniendo los costos de mantenimiento bajos.\n- Estado: Inmueble en buen estado usado y bien conservado.\n\nIdeal para: Profesionales independientes, startups, consultorios y pequeñas empresas que buscan una ubicación estratégica y ahorro en amoblamiento.\n\n¡Agenda tu cita y conoce tu próximo espacio de trabajo!\n\nPalabras clave: oficina en renta, oficina en el cable, arriendo cable estrato 5, oficina 43m2, oficina amoblada, alquiler oficina, oficina con parqueadero, canon incluye administracion, inmuebles cable.',
      departamento: 'Caldas',
      ciudad: 'Manizales',
      barrio_sector: 'El Cable',
      estrato: 5,
      tipo_operacion: 'arriendo',
      tipo_propiedad: 'oficina',
      precio: 1920000,
      valor_administracion: 0,
      es_negociable: false,
      area_construida: 43,
      habitaciones: 0,
      banos_completos: 0,
      parqueaderos: 1,
      estado_inmueble: 'used',
      estado_amoblado: 'amoblado',
      tiene_balcon: false,
      tiene_gimnasio: false,
      tiene_piscina_comun: false,
      tiene_ascensor: true,
      tiene_porteria_24h: true,
      tiene_zonas_verdes: false,
      tiene_cancha_futbol: false,
      tiene_kiosko_asados: false,
      tiene_salon_social: false,
      tiene_juegos_infantiles: false,
      tiene_sendero_peatonal: false,
      imagenes: [
        { id: 'img-oc-ex1', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczOrS5iSqaVQF-jBf94vPvLeR0-NN-d1UEVQR7JZ_OWRCK3pLVlxAc_gOIJdHzMa5krZW2NbIoZyKjGxnOvpWBDgOYyow8s4ls3T6yiWPOKFrHujxXgktm3CS5rFve2mkJ5GzdTmfQxo3hNWwqG_Ez_-=w1437-h945-s-no-gm?authuser=0', es_principal: true },
        { id: 'img-oc-ex2', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczN_kEyRojML6xxhyrcF0eydw0cFmToTybqxLnWyJjj-sDpEZ_4cPRJ1Xe1h6RTayMvKjL5_m85g1zpzqfBuboasH3hNuaHJ6xxGiVFhvOQ3F9I1007dvywYAYwNEmcJxQYMsTunLfkZVdTuSI0OZ4iJ=w1600-h876-s-no-gm?authuser=0', es_principal: false },
        { id: 'img-oc-ex2', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczMOO50T_HKasMSvst7_353OyE12wx676QrUB0Lvone6Daj4OOM4Wx8KSnHIAHghNB9LGiFK7T_HZU4LGml7Y8DyhEYTZDyhY0C4vfY99UHPTP__LPNKQ81T2x5cpnYfbdc8uTmO-DkzQHygZChpLTQs=w531-h945-s-no-gm?authuser=0', es_principal: false },
        { id: 'img-oc-ex2', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczMoYXtR0sm3twVbM72qOjIlShGbM1uV7le3XY13t4qPe6ceOrKXvhgJjInRCPoglO0AR8Gc1Z3X-Tj2QNpTdyZy1pjoC6RMfRoIvRDs0eJw9aVyU6cgHY6TUY34109wgvP1XJJz5rCFlBesJSL-FFHs=w1437-h945-s-no-gm?authuser=0', es_principal: false },
        { id: 'img-oc-ex2', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczNT7rmcSwSj4RimLKz0aN2OxVlYH-MW1Ba9GT4DtCFZnKJZgd4anoJwzVYQPNn3xafeyNRh7I5PUmZECi0r7V78O8aA5m4JvHf8uLE579kMrJ3GbDNu0augP2apVWiztP_ARLoTY_wccV5wGL79xmLU=w531-h945-s-no-gm?authuser=0', es_principal: false },
        { id: 'img-oc-ex2', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczNyoNQFm3ibDcT0j4rsspDwzn3lo1VgdDJiXupwXYXtsyeoM7Koj36XStaIb7GPmZGLGGdzBCYxnkdvVMjDdLnJhgJgsFvZIvPLEH50Z8AyxaNbIscRiuqEx_0fziQpkmefp2GXaRBYPquu6OyOZ3rX=w531-h945-s-no-gm?authuser=0', es_principal: false },
        { id: 'img-oc-ex2', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczPiROODVmExWXltCsiATStBZHMACP3uF7Y9vLakpRkYrbbowqbMaoSQvKUm_ms1qm0LnMoQoH76x1rUDNqDCFPfom_WJ3xVQAvDFSJlRHnRyR8CA9LtmEVlXq-LubnG2RTN2H3k3CBKf0-t0a_EPtgc=w531-h945-s-no-gm?authuser=0', es_principal: false },
        { id: 'img-oc-ex2', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczOp2gpdsDWjJfj2HvbAyXfUjMkp6ieJactu9cycrc86fEsBj7AtZMgBOO5lqzgRSIRu-7watsQtNbXvEMg39qaLOd2wNcfs5RUOXfGwxeT1tdapAeFvEDJBOiG7AsLYYrtvD1HQQKIQQEFGqVqsA7V6=w531-h945-s-no-gm?authuser=0', es_principal: false },
      ],
      es_destacado: false,
      estado_publicacion: 'publicado',
      fecha_publicacion: new Date().toISOString(),
    },
    {
      id: 'arriendo-local-sanjorge',
      titulo: 'Local Comercial en Arriendo en Avenida Principal de San Jorge',
      descripcion: "Local comercial de 65 m² en arriendo, ubicado en el Barrio San Jorge sobre la avenida principal. Dimensiones: Alto 2.55 M, Ancho 5.40 M, Fondo 12 M. Cuenta con 1 baño (poceta).",
      departamento: 'Caldas',
      ciudad: 'Manizales',
      barrio_sector: 'San Jorge',
      estrato: 3,
      tipo_operacion: 'arriendo',
      tipo_propiedad: 'local',
      precio: 3400000,
      valor_administracion: undefined,
      es_negociable: false,
      area_construida: 65,
      habitaciones: 0,
      banos_completos: 1,
      parqueaderos: 0,
      estado_inmueble: 'used',
      estado_amoblado: 'sin_amoblar',
      tiene_balcon: false,
      tiene_gimnasio: false,
      tiene_piscina_comun: false,
      tiene_ascensor: false,
      tiene_porteria_24h: false,
      tiene_zonas_verdes: false,
      tiene_cancha_futbol: false,
      tiene_kiosko_asados: false,
      tiene_salon_social: false,
      tiene_juegos_infantiles: false,
      tiene_sendero_peatonal: false,
      imagenes: [
        { id: 'img-lsj1', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczO_vR1MGIY9VtndWNgIdJgQPJZeyr8yjqZRSRJS6FWTM6QgM2q6gzomzQREKLsxty5owHMG-vh0OtclR-D-Wrn_Szvp_EhPJg02T4yleGgN2xjP5ZVEkruqNDFBEeSv_nflNvZfBm-fFPsN_SuhJQzS=w751-h945-s-no-gm?authuser=0', es_principal: true },
        { id: 'img-lsj2', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczMbUqlf7TVV47rd3g3YesivhGX3p-oXW6TlhFXWSTyzjVznAGA7UqQu363CvY5VYuxcRfz6jvWbIt5rl2h-9JxSVrPHsFWez7kfeA1SudNkxyF3qut1pt3rn-NRtGaCbMsy9oDCEI8lXzBCcRK5Bw7o=w1072-h945-s-no-gm?authuser=0', es_principal: false },
        { id: 'img-lsj3', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczOmIyBesI3sjNez--3ObgARMVVrrQpZznXMDoGn71c2mIAC2xtV1llhuvPE3HrVEeeu3NOe1whzSU3N_Q1HMQLka4zWNTtoUD0F5yDxUPxQK5g8k08y_5556OpKZ84hCi7fRoeBt1JnpV8l9xCXsgVU=w531-h945-s-no-gm?authuser=0', es_principal: false },
        { id: 'img-lsj4', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczOThzwmCP9qSvvIcBsKiCqxbdxfXnImRdBgeWmOxinpQB-wzX0t66gWpP4VAdQ7INeChfFJkLX7-hP2MDC9qoGvXa13YyRzdsYdOo3u7eOf5CpOfe0dvf9sHKqIR5SEZh9bB6EskUei9PFiOzJddiiM=w531-h945-s-no-gm?authuser=0', es_principal: false },
        { id: 'img-lsj5', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczPoRzwNkN9iL7mX84Qz6X1PLRnSp2S5MLZb6yEHLEID268JfUi7uv8ZyPqWJC8f20RSLLQhFpmUYbr7Yc3JXWM3uCcy_pEWq6cdl3C2RD98ZVC7i4p01xMlqOFR6RTDYAj72OFBekrxlendhCFfUSVG=w1208-h945-s-no-gm?authuser=0', es_principal: false },
        { id: 'img-lsj6', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczNHRSltBURH_yDC5VuWb2Dvw3DWO8opSREJzlIlAXyD68g4r074Q6VYReJ31PchJ9HkrhXCI5qhSar4NFOJtvGfysPRtvtsyXs6me9f0HnUdBP0U_78KWNuN6Jt6eR5Ig10x705bIwtcch5pYB_CrHv=w531-h945-s-no-gm?authuser=0', es_principal: false },
        { id: 'img-lsj7', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczNPfFgNr1LMwimmDZcjnXSCh-HfAkZvwpVIa7g8vaEpoXVb4h396fXKvkdKLPma4bVeT4KFmN-Tv8dChBsHPKFQJqTIFKddqDBeCGukhmh8qtVKDcwQCswlwU1Z-Hw-J2On6L6DI6kz1oXPLl-t6cYU=w531-h945-s-no-gm?authuser=0', es_principal: false },
        { id: 'img-lsj8', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczP771Utbvtqf6ZFwghigjCATVvxkHoD2gkTJaz-RDD_br71ZlVo3Zu9HSXFnh3Bn1Wuv37PoAgwsAf0C9czsfRy0OTZK-o5NzDVjhOmRWlxbpEZZUTiqekVbkGOPvzmpr7Vp9Gj0dsaCETlZvpHGwl-=w531-h945-s-no-gm?authuser=0', es_principal: false },
        { id: 'img-lsj9', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczPSFKG4zySk5Yk-1dk5gjx74Cpxf1Tb2v78t5rAG2lzNkf8RKw_axism00hoZHWzPjRiugSF1eqQS2Y2F1h9pws85EkIuIXre0sGDPCom6XHbLrsuRnxlQ5brutLXW16OuiFSBgxG4I_r45K-87pY_W=w1015-h945-s-no-gm?authuser=0', es_principal: false },
        { id: 'img-lsj10', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczOow4OHbz9iLFXEeeUDQIL_K5OWr0_GNrpcX_AtDgjf4weGixrr2fwCwdS9BSN8lM_G5JNzfCzYgXIE0OMc4gcTDMFF6RGUKQi-VUv1TmBGgY5sz8VRGB_knHW2L82vBh2M6KHptJAN_eKX9V6O02-3=w1016-h945-s-no-gm?authuser=0', es_principal: false },
        { id: 'img-lsj11', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczPjysBep5Bgl7JDhMiDVmuVVfo9-1Y-enNIZGxvURyNF9_z3V5_P83d-OocwtYXaNzdVdz6Rcui0c7ZH_WNAqJ2JbvKu1_nrZl4X3EEjKVm63c-PRpFT9HcuMpWypx4TGOpINRRup7U7pROwdOH0EGM=w531-h945-s-no-gm?authuser=0', es_principal: false },
        { id: 'img-lsj12', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczMiXtZ-BZa75fH12zM8w_p209SHRher28UZKovHAn0NvWpe-tm8GZAURLHi3dbaC3bs1cAntlQWOEqFAeqWo5A2_Fh2IBxza0cAHp2lG0460WNWlxP815S-rJh8XWMTrgZv8085FrRqcJVlXz6NLTBM=w1290-h945-s-no-gm?authuser=0', es_principal: false },
        { id: 'img-lsj13', url_imagen: 'https://lh3.googleusercontent.com/pw/AP1GczNkd_Mpo3xlWFiZ2FjjrblmvjGFkwJw4xIZnU8M=w1259-h945-s-no-gm?authuser=0', es_principal: false },
      ],
      es_destacado: false,
      estado_publicacion: 'publicado',
      fecha_publicacion: new Date().toISOString(),
    },
];

// FIX: Added parentheses around the intersection type to ensure it's an array of the combined type,
// not an intersection of a type and an array type.
export const TESTIMONIALS: (Omit<Testimonial, 'comment'> & { commentKey: string })[] = [
  {
    name: 'Carlos Mendoza',
    rating: 5,
    commentKey: 'testimonials.carlosMendoza',
    avatar: 'https://randomuser.me/api/portraits/men/32.jpg',
  },
  {
    name: 'Ana Sofía Restrepo',
    rating: 5,
    commentKey: 'testimonials.anaSofiaRestrepo',
    avatar: 'https://randomuser.me/api/portraits/women/44.jpg',
  },
  {
    name: 'Javier Correa',
    rating: 4.5,
    commentKey: 'testimonials.javierCorrea',
    avatar: 'https://randomuser.me/api/portraits/men/46.jpg',
  },
  {
    name: 'Lucía Vélez',
    rating: 5,
    commentKey: 'testimonials.luciaVelez',
    avatar: 'https://randomuser.me/api/portraits/women/31.jpg',
  },
  {
    name: 'Ricardo Palacio',
    rating: 4,
    commentKey: 'testimonials.ricardoPalacio',
    avatar: 'https://randomuser.me/api/portraits/men/60.jpg',
  },
  {
    name: 'Isabella Giraldo',
    rating: 5,
    commentKey: 'testimonials.isabellaGiraldo',
    avatar: 'https://randomuser.me/api/portraits/women/68.jpg',
  },
  {
    name: 'Mateo Arango',
    rating: 4.5,
    commentKey: 'testimonials.mateoArango',
    avatar: 'https://randomuser.me/api/portraits/men/78.jpg',
  },
  {
    name: 'Valentina Hoyos',
    rating: 5,
    commentKey: 'testimonials.valentinaHoyos',
    avatar: 'https://randomuser.me/api/portraits/women/8.jpg',
  },
  {
    name: 'Andrés Castaño',
    rating: 4,
    commentKey: 'testimonials.andresCastano',
    avatar: 'https://randomuser.me/api/portraits/men/11.jpg',
  },
  {
    name: 'Daniela Franco',
    rating: 5,
    commentKey: 'testimonials.danielaFranco',
    avatar: 'https://randomuser.me/api/portraits/women/17.jpg',
  }
];